const kidStatusTest = [
    {classId: 8, kidId: "HD027", status: 0},
    {classId: 4, kidId: "HD429", status: 0},
    {classId: 6, kidId: "HD143", status: 0},
    {classId: 3, kidId: "HD437", status: 1},
    {classId: 9, kidId: "HD156", status: 1},
    {classId: 3, kidId: "HD015", status: 0},
    {classId: 9, kidId: "HD383", status: 0},
    {classId: 11, kidId: "HD012", status: 1},
    {classId: 8, kidId: "HD167", status: 1},
    {classId: 1, kidId: "HD445", status: 1},
    {classId: 2, kidId: "HD051", status: 1},
    {classId: 0, kidId: "HD315", status: 0},
    {classId: 1, kidId: "HD400", status: 0},
    {classId: 3, kidId: "HD319", status: 0},
    {classId: 9, kidId: "HD388", status: 1},
    {classId: 4, kidId: "HD052", status: 0},
    {classId: 1, kidId: "HD461", status: 0},
    {classId: 1, kidId: "HD318", status: 1},
    {classId: 9, kidId: "HD252", status: 1},
    {classId: 3, kidId: "HD019", status: 0},
    {classId: 2, kidId: "HD424", status: 1},
    {classId: 4, kidId: "HD293", status: 0},
    {classId: 2, kidId: "HD408", status: 0},
    {classId: 6, kidId: "HD113", status: 0},
    {classId: 5, kidId: "HD187", status: 0},
    {classId: 8, kidId: "HD104", status: 0},
    {classId: 9, kidId: "HD062", status: 0},
    {classId: 8, kidId: "HD256", status: 1},
    {classId: 7, kidId: "HD333", status: 0},
    {classId: 9, kidId: "HD064", status: 2},
    {classId: 0, kidId: "HD387", status: 1},
    {classId: 2, kidId: "HD447", status: 0},
    {classId: 6, kidId: "HD226", status: 1},
    {classId: 3, kidId: "HD046", status: 0},
    {classId: 5, kidId: "HD136", status: 0},
    {classId: 0, kidId: "HD317", status: 1},
    {classId: 4, kidId: "HD128", status: 0},
    {classId: 4, kidId: "HD286", status: 0},
    {classId: 2, kidId: "HD347", status: 0},
    {classId: 4, kidId: "HD410", status: 2},
    {classId: 8, kidId: "HD222", status: 1},
    {classId: 11, kidId: "HD194", status: 1},
    {classId: 1, kidId: "HD473", status: 0},
    {classId: 9, kidId: "HD426", status: 0},
    {classId: 10, kidId: "HD171", status: 1},
    {classId: 10, kidId: "HD178", status: 0},
    {classId: 7, kidId: "HD184", status: 0},
    {classId: 5, kidId: "HD202", status: 0},
    {classId: 6, kidId: "HD038", status: 0},
    {classId: 6, kidId: "HD274", status: 0},
    {classId: 9, kidId: "HD308", status: 0},
    {classId: 0, kidId: "HD435", status: 3},
    {classId: 5, kidId: "HD140", status: 1},
    {classId: 4, kidId: "HD326", status: 1},
    {classId: 6, kidId: "HD149", status: 0},
    {classId: 9, kidId: "HD155", status: 0},
    {classId: 9, kidId: "HD107", status: 0},
    {classId: 3, kidId: "HD367", status: 1},
    {classId: 3, kidId: "HD053", status: 0},
    {classId: 0, kidId: "HD349", status: 0},
    {classId: 8, kidId: "HD096", status: 0},
    {classId: 4, kidId: "HD119", status: 0},
    {classId: 4, kidId: "HD466", status: 1},
    {classId: 8, kidId: "HD028", status: 1},
    {classId: 6, kidId: "HD039", status: 3},
    {classId: 1, kidId: "HD006", status: 0},
    {classId: 4, kidId: "HD364", status: 0},
    {classId: 8, kidId: "HD092", status: 0},
    {classId: 2, kidId: "HD214", status: 0},
    {classId: 10, kidId: "HD305", status: 1},
    {classId: 1, kidId: "HD370", status: 1},
    {classId: 8, kidId: "HD158", status: 0},
    {classId: 2, kidId: "HD416", status: 1},
    {classId: 0, kidId: "HD459", status: 1},
    {classId: 2, kidId: "HD358", status: 1},
    {classId: 11, kidId: "HD199", status: 1},
    {classId: 3, kidId: "HD307", status: 1},
    {classId: 5, kidId: "HD303", status: 0},
    {classId: 7, kidId: "HD100", status: 1},
    {classId: 7, kidId: "HD114", status: 1},
    {classId: 9, kidId: "HD154", status: 1},
    {classId: 8, kidId: "HD153", status: 0},
    {classId: 4, kidId: "HD049", status: 0},
    {classId: 8, kidId: "HD264", status: 2},
    {classId: 4, kidId: "HD287", status: 0},
    {classId: 2, kidId: "HD448", status: 0},
    {classId: 6, kidId: "HD109", status: 0},
    {classId: 8, kidId: "HD101", status: 0},
    {classId: 8, kidId: "HD255", status: 0},
    {classId: 0, kidId: "HD355", status: 1},
    {classId: 1, kidId: "HD460", status: 0},
    {classId: 4, kidId: "HD120", status: 0},
    {classId: 3, kidId: "HD401", status: 1},
    {classId: 2, kidId: "HD475", status: 0},
    {classId: 8, kidId: "HD228", status: 1},
    {classId: 1, kidId: "HD314", status: 0},
    {classId: 9, kidId: "HD081", status: 0},
    {classId: 6, kidId: "HD227", status: 0},
    {classId: 3, kidId: "HD188", status: 2},
    {classId: 9, kidId: "HD072", status: 0},
    {classId: 8, kidId: "HD152", status: 0},
    {classId: 2, kidId: "HD417", status: 0},
    {classId: 5, kidId: "HD190", status: 0},
    {classId: 6, kidId: "HD133", status: 0},
    {classId: 4, kidId: "HD464", status: 1},
    {classId: 7, kidId: "HD322", status: 0},
    {classId: 7, kidId: "HD421", status: 0},
    {classId: 2, kidId: "HD207", status: 0},
    {classId: 2, kidId: "HD353", status: 1},
    {classId: 0, kidId: "HD431", status: 0},
    {classId: 8, kidId: "HD323", status: 1},
    {classId: 5, kidId: "HD142", status: 1},
    {classId: 4, kidId: "HD356", status: 1},
    {classId: 9, kidId: "HD244", status: 0},
    {classId: 7, kidId: "HD390", status: 0},
    {classId: 8, kidId: "HD257", status: 0},
    {classId: 3, kidId: "HD425", status: 0},
    {classId: 5, kidId: "HD017", status: 1},
    {classId: 0, kidId: "HD208", status: 0},
    {classId: 7, kidId: "HD057", status: 1},
    {classId: 7, kidId: "HD060", status: 0},
    {classId: 8, kidId: "HD151", status: 1},
    {classId: 5, kidId: "HD147", status: 0},
    {classId: 9, kidId: "HD320", status: 0},
    {classId: 6, kidId: "HD148", status: 0},
    {classId: 4, kidId: "HD393", status: 0},
    {classId: 10, kidId: "HD321", status: 1},
    {classId: 5, kidId: "HD195", status: 0},
    {classId: 2, kidId: "HD294", status: 1},
    {classId: 4, kidId: "HD334", status: 1},
    {classId: 9, kidId: "HD087", status: 0},
    {classId: 3, kidId: "HD474", status: 0},
    {classId: 9, kidId: "HD238", status: 1},
    {classId: 9, kidId: "HD160", status: 0},
    {classId: 0, kidId: "HD444", status: 0},
    {classId: 10, kidId: "HD176", status: 0},
    {classId: 6, kidId: "HD137", status: 0},
    {classId: 2, kidId: "HD457", status: 0},
    {classId: 9, kidId: "HD250", status: 1},
    {classId: 5, kidId: "HD013", status: 0},
    {classId: 9, kidId: "HD242", status: 0},
    {classId: 3, kidId: "HD004", status: 0},
    {classId: 8, kidId: "HD164", status: 0},
    {classId: 10, kidId: "HD177", status: 0},
    {classId: 3, kidId: "HD325", status: 0},
    {classId: 7, kidId: "HD427", status: 0},
    {classId: 0, kidId: "HD418", status: 3},
    {classId: 5, kidId: "HD197", status: 1},
    {classId: 3, kidId: "HD375", status: 0},
    {classId: 8, kidId: "HD102", status: 0},
    {classId: 6, kidId: "HD382", status: 0},
    {classId: 2, kidId: "HD371", status: 0},
    {classId: 4, kidId: "HD449", status: 1},
    {classId: 8, kidId: "HD261", status: 0},
    {classId: 9, kidId: "HD273", status: 1},
    {classId: 7, kidId: "HD182", status: 1},
    {classId: 9, kidId: "HD063", status: 0},
    {classId: 9, kidId: "HD251", status: 1},
    {classId: 6, kidId: "HD225", status: 0},
    {classId: 8, kidId: "HD262", status: 1},
    {classId: 9, kidId: "HD085", status: 0},
    {classId: 0, kidId: "HD463", status: 1},
    {classId: 9, kidId: "HD090", status: 0},
    {classId: 0, kidId: "HD441", status: 0},
    {classId: 8, kidId: "HD269", status: 1},
    {classId: 0, kidId: "HD454", status: 0},
    {classId: 4, kidId: "HD010", status: 0},
    {classId: 4, kidId: "HD285", status: 0},
    {classId: 8, kidId: "HD351", status: 0},
    {classId: 8, kidId: "HD309", status: 1},
    {classId: 2, kidId: "HD433", status: 1},
    {classId: 6, kidId: "HD043", status: 0},
    {classId: 3, kidId: "HD024", status: 0},
    {classId: 0, kidId: "HD477", status: 0},
    {classId: 6, kidId: "HD381", status: 0},
    {classId: 8, kidId: "HD276", status: 0},
    {classId: 8, kidId: "HD123", status: 0},
    {classId: 9, kidId: "HD076", status: 0},
    {classId: 7, kidId: "HD170", status: 0},
    {classId: 8, kidId: "HD292", status: 0},
    {classId: 1, kidId: "HD451", status: 0},
    {classId: 8, kidId: "HD296", status: 0},
    {classId: 6, kidId: "HD025", status: 0},
    {classId: 2, kidId: "HD470", status: 0},
    {classId: 5, kidId: "HD201", status: 0},
    {classId: 1, kidId: "HD392", status: 1},
    {classId: 4, kidId: "HD112", status: 0},
    {classId: 4, kidId: "HD001", status: 0},
    {classId: 8, kidId: "HD031", status: 0},
    {classId: 8, kidId: "HD110", status: 0},
    {classId: 4, kidId: "HD118", status: 0},
    {classId: 6, kidId: "HD230", status: 0},
    {classId: 2, kidId: "HD361", status: 0},
    {classId: 0, kidId: "HD422", status: 0},
    {classId: 0, kidId: "HD008", status: 0},
    {classId: 1, kidId: "HD471", status: 0},
    {classId: 5, kidId: "HD021", status: 0},
    {classId: 10, kidId: "HD174", status: 0},
    {classId: 6, kidId: "HD144", status: 0},
    {classId: 7, kidId: "HD341", status: 0},
    {classId: 8, kidId: "HD229", status: 1},
    {classId: 9, kidId: "HD069", status: 0},
    {classId: 7, kidId: "HD312", status: 0},
    {classId: 1, kidId: "HD291", status: 0},
    {classId: 9, kidId: "HD162", status: 0},
    {classId: 9, kidId: "HD161", status: 1},
    {classId: 4, kidId: "HD302", status: 0},
    {classId: 2, kidId: "HD406", status: 0},
    {classId: 8, kidId: "HD098", status: 0},
    {classId: 8, kidId: "HD313", status: 0},
    {classId: 9, kidId: "HD068", status: 1},
    {classId: 3, kidId: "HD210", status: 1},
    {classId: 7, kidId: "HD073", status: 1},
    {classId: 3, kidId: "HD316", status: 0},
    {classId: 1, kidId: "HD020", status: 0},
    {classId: 8, kidId: "HD265", status: 0},
    {classId: 8, kidId: "HD169", status: 1},
    {classId: 1, kidId: "HD345", status: 0},
    {classId: 1, kidId: "HD011", status: 0},
    {classId: 1, kidId: "HD023", status: 0},
    {classId: 8, kidId: "HD232", status: 1},
    {classId: 0, kidId: "HD430", status: 0},
    {classId: 9, kidId: "HD071", status: 1},
    {classId: 7, kidId: "HD131", status: 0},
    {classId: 9, kidId: "HD026", status: 0},
    {classId: 2, kidId: "HD394", status: 0},
    {classId: 1, kidId: "HD352", status: 1},
    {classId: 4, kidId: "HD116", status: 0},
    {classId: 9, kidId: "HD056", status: 0},
    {classId: 4, kidId: "HD379", status: 1},
    {classId: 0, kidId: "HD436", status: 0},
    {classId: 8, kidId: "HD106", status: 0},
    {classId: 5, kidId: "HD209", status: 0},
    {classId: 8, kidId: "HD258", status: 0},
    {classId: 1, kidId: "HD290", status: 1},
    {classId: 3, kidId: "HD423", status: 1},
    {classId: 2, kidId: "HD432", status: 1},
    {classId: 9, kidId: "HD240", status: 4},
    {classId: 7, kidId: "HD236", status: 0},
    {classId: 0, kidId: "HD346", status: 0},
    {classId: 1, kidId: "HD009", status: 0},
    {classId: 5, kidId: "HD018", status: 0},
    {classId: 8, kidId: "HD166", status: 0},
    {classId: 1, kidId: "HD386", status: 0},
    {classId: 7, kidId: "HD389", status: 0},
    {classId: 8, kidId: "HD270", status: 1},
    {classId: 3, kidId: "HD336", status: 0},
    {classId: 8, kidId: "HD033", status: 0},
    {classId: 9, kidId: "HD035", status: 0},
    {classId: 5, kidId: "HD139", status: 0},
    {classId: 9, kidId: "HD150", status: 0},
    {classId: 5, kidId: "HD306", status: 0},
    {classId: 9, kidId: "HD245", status: 1},
    {classId: 9, kidId: "HD283", status: 2},
    {classId: 1, kidId: "HD337", status: 0},
    {classId: 3, kidId: "HD311", status: 0},
    {classId: 4, kidId: "HD350", status: 1},
    {classId: 6, kidId: "HD342", status: 1},
    {classId: 9, kidId: "HD413", status: 0},
    {classId: 9, kidId: "HD247", status: 1},
    {classId: 0, kidId: "HD465", status: 0},
    {classId: 8, kidId: "HD267", status: 0},
    {classId: 9, kidId: "HD083", status: 0},
    {classId: 8, kidId: "HD440", status: 0},
    {classId: 2, kidId: "HD007", status: 4},
    {classId: 0, kidId: "HD363", status: 0},
    {classId: 1, kidId: "HD014", status: 0},
    {classId: 9, kidId: "HD234", status: 0},
    {classId: 2, kidId: "HD301", status: 1},
    {classId: 8, kidId: "HD329", status: 0},
    {classId: 6, kidId: "HD002", status: 0},
    {classId: 6, kidId: "HD146", status: 0},
    {classId: 4, kidId: "HD129", status: 0},
    {classId: 9, kidId: "HD241", status: 0},
    {classId: 5, kidId: "HD130", status: 0},
    {classId: 2, kidId: "HD044", status: 1},
    {classId: 0, kidId: "HD411", status: 0},
    {classId: 3, kidId: "HD218", status: 1},
    {classId: 3, kidId: "HD468", status: 0},
    {classId: 4, kidId: "HD402", status: 0},
    {classId: 0, kidId: "HD212", status: 1},
    {classId: 6, kidId: "HD233", status: 1},
    {classId: 0, kidId: "HD213", status: 0},
    {classId: 8, kidId: "HD094", status: 1},
    {classId: 5, kidId: "HD050", status: 0},
    {classId: 4, kidId: "HD297", status: 1},
    {classId: 1, kidId: "HD366", status: 1},
    {classId: 9, kidId: "HD105", status: 0},
    {classId: 0, kidId: "HD338", status: 1},
    {classId: 8, kidId: "HD266", status: 0},
    {classId: 5, kidId: "HD205", status: 0},
    {classId: 4, kidId: "HD124", status: 0},
    {classId: 5, kidId: "HD219", status: 4},
    {classId: 2, kidId: "HD054", status: 1},
    {classId: 2, kidId: "HD295", status: 0},
    {classId: 1, kidId: "HD380", status: 0},
    {classId: 5, kidId: "HD196", status: 0},
    {classId: 1, kidId: "HD281", status: 1},
    {classId: 5, kidId: "HD145", status: 0},
    {classId: 9, kidId: "HD032", status: 0},
    {classId: 7, kidId: "HD067", status: 0},
    {classId: 2, kidId: "HD372", status: 0},
    {classId: 11, kidId: "HD189", status: 1},
    {classId: 2, kidId: "HD405", status: 0},
    {classId: 2, kidId: "HD438", status: 1},
    {classId: 7, kidId: "HD061", status: 0},
    {classId: 1, kidId: "HD005", status: 2},
    {classId: 1, kidId: "HD450", status: 0},
    {classId: 1, kidId: "HD407", status: 1},
    {classId: 1, kidId: "HD412", status: 1},
    {classId: 6, kidId: "HD115", status: 0},
    {classId: 8, kidId: "HD163", status: 0},
    {classId: 3, kidId: "HD055", status: 1},
    {classId: 6, kidId: "HD134", status: 0},
    {classId: 3, kidId: "HD206", status: 1},
    {classId: 7, kidId: "HD277", status: 4},
    {classId: 2, kidId: "HD377", status: 0},
    {classId: 3, kidId: "HD180", status: 0},
    {classId: 7, kidId: "HD066", status: 0},
    {classId: 4, kidId: "HD126", status: 2},
    {classId: 4, kidId: "HD328", status: 1},
    {classId: 6, kidId: "HD036", status: 1},
    {classId: 2, kidId: "HD360", status: 1},
    {classId: 9, kidId: "HD091", status: 0},
    {classId: 8, kidId: "HD108", status: 0},
    {classId: 5, kidId: "HD304", status: 0},
    {classId: 7, kidId: "HD235", status: 0},
    {classId: 8, kidId: "HD260", status: 1},
    {classId: 6, kidId: "HD374", status: 0},
    {classId: 3, kidId: "HD368", status: 0},
    {classId: 3, kidId: "HD469", status: 0},
    {classId: 4, kidId: "HD455", status: 0},
    {classId: 6, kidId: "HD103", status: 1},
    {classId: 8, kidId: "HD042", status: 0},
    {classId: 1, kidId: "HD300", status: 1},
    {classId: 8, kidId: "HD095", status: 1},
    {classId: 8, kidId: "HD165", status: 0},
    {classId: 2, kidId: "HD458", status: 2},
    {classId: 1, kidId: "HD357", status: 0},
    {classId: 9, kidId: "HD089", status: 1},
    {classId: 6, kidId: "HD030", status: 0},
    {classId: 9, kidId: "HD243", status: 0},
    {classId: 7, kidId: "HD332", status: 4},
    {classId: 6, kidId: "HD117", status: 0},
    {classId: 4, kidId: "HD216", status: 2},
    {classId: 5, kidId: "HD327", status: 0},
    {classId: 5, kidId: "HD138", status: 0},
    {classId: 4, kidId: "HD279", status: 0},
    {classId: 9, kidId: "HD065", status: 2},
    {classId: 1, kidId: "HD443", status: 0},
    {classId: 8, kidId: "HD263", status: 3},
    {classId: 7, kidId: "HD070", status: 0},
    {classId: 7, kidId: "HD362", status: 0},
    {classId: 5, kidId: "HD198", status: 0},
    {classId: 1, kidId: "HD343", status: 0},
    {classId: 4, kidId: "HD280", status: 0},
    {classId: 9, kidId: "HD079", status: 0},
    {classId: 5, kidId: "HD462", status: 0},
    {classId: 9, kidId: "HD157", status: 1},
    {classId: 7, kidId: "HD040", status: 0},
    {classId: 5, kidId: "HD339", status: 1},
    {classId: 9, kidId: "HD084", status: 1},
    {classId: 8, kidId: "HD298", status: 0},
    {classId: 0, kidId: "HD419", status: 0},
    {classId: 1, kidId: "HD398", status: 0},
    {classId: 2, kidId: "HD467", status: 0},
    {classId: 2, kidId: "HD344", status: 0},
    {classId: 7, kidId: "HD175", status: 0},
    {classId: 6, kidId: "HD122", status: 0},
    {classId: 7, kidId: "HD121", status: 0},
    {classId: 7, kidId: "HD354", status: 1},
    {classId: 10, kidId: "HD179", status: 0},
    {classId: 1, kidId: "HD446", status: 0},
    {classId: 2, kidId: "HD385", status: 0},
    {classId: 7, kidId: "HD237", status: 1},
    {classId: 9, kidId: "HD249", status: 1},
    {classId: 7, kidId: "HD289", status: 0},
    {classId: 4, kidId: "HD414", status: 0},
    {classId: 9, kidId: "HD391", status: 3},
    {classId: 9, kidId: "HD282", status: 0},
    {classId: 5, kidId: "HD310", status: 1},
    {classId: 2, kidId: "HD428", status: 0},
    {classId: 7, kidId: "HD186", status: 0},
    {classId: 2, kidId: "HD478", status: 1},
    {classId: 4, kidId: "HD288", status: 0},
    {classId: 6, kidId: "HD097", status: 0},
    {classId: 8, kidId: "HD029", status: 0},
    {classId: 2, kidId: "HD378", status: 0},
    {classId: 9, kidId: "HD077", status: 2},
    {classId: 7, kidId: "HD442", status: 0},
    {classId: 4, kidId: "HD192", status: 1},
    {classId: 3, kidId: "HD284", status: 0},
    {classId: 9, kidId: "HD093", status: 0},
    {classId: 1, kidId: "HD324", status: 0},
    {classId: 3, kidId: "HD299", status: 0},
    {classId: 2, kidId: "HD369", status: 0},
    {classId: 3, kidId: "HD452", status: 0},
    {classId: 8, kidId: "HD331", status: 0},
    {classId: 2, kidId: "HD476", status: 0},
    {classId: 10, kidId: "HD275", status: 0},
    {classId: 1, kidId: "HD373", status: 1},
    {classId: 9, kidId: "HD078", status: 0},
    {classId: 3, kidId: "HD172", status: 0},
    {classId: 3, kidId: "HD191", status: 1},
    {classId: 11, kidId: "HD203", status: 1},
    {classId: 4, kidId: "HD397", status: 0},
    {classId: 7, kidId: "HD456", status: 1},
    {classId: 9, kidId: "HD088", status: 0},
    {classId: 4, kidId: "HD220", status: 0},
    {classId: 2, kidId: "HD335", status: 1},
    {classId: 9, kidId: "HD037", status: 0},
    {classId: 8, kidId: "HD259", status: 0},
    {classId: 5, kidId: "HD359", status: 1},
    {classId: 9, kidId: "HD272", status: 1},
    {classId: 0, kidId: "HD420", status: 1},
    {classId: 7, kidId: "HD340", status: 1},
    {classId: 8, kidId: "HD330", status: 0},
    {classId: 3, kidId: "HD439", status: 0},
    {classId: 7, kidId: "HD204", status: 0},
    {classId: 10, kidId: "HD173", status: 1},
    {classId: 5, kidId: "HD132", status: 0},
    {classId: 7, kidId: "HD185", status: 2},
    {classId: 1, kidId: "HD403", status: 0},
    {classId: 0, kidId: "HD003", status: 0},
    {classId: 9, kidId: "HD058", status: 0},
    {classId: 8, kidId: "HD159", status: 1},
    {classId: 6, kidId: "HD141", status: 0},
    {classId: 5, kidId: "HD200", status: 0},
    {classId: 8, kidId: "HD271", status: 1},
    {classId: 9, kidId: "HD059", status: 0},
    {classId: 4, kidId: "HD472", status: 0},
    {classId: 9, kidId: "HD075", status: 0},
    {classId: 1, kidId: "HD365", status: 1},
    {classId: 9, kidId: "HD082", status: 0},
    {classId: 0, kidId: "HD404", status: 1},
    {classId: 9, kidId: "HD074", status: 1},
    {classId: 8, kidId: "HD248", status: 0},
    {classId: 1, kidId: "HD415", status: 0},
    {classId: 8, kidId: "HD168", status: 1},
    {classId: 5, kidId: "HD127", status: 1},
    {classId: 4, kidId: "HD396", status: 0},
    {classId: 3, kidId: "HD016", status: 1},
    {classId: 0, kidId: "HD453", status: 0},
    {classId: 3, kidId: "HD193", status: 0},
    {classId: 6, kidId: "HD111", status: 1},
    {classId: 6, kidId: "HD231", status: 1},
    {classId: 2, kidId: "HD047", status: 0},
    {classId: 2, kidId: "HD048", status: 1},
    {classId: 7, kidId: "HD434", status: 0},
    {classId: 4, kidId: "HD409", status: 0},
    {classId: 7, kidId: "HD395", status: 0},
    {classId: 3, kidId: "HD399", status: 0},
    {classId: 4, kidId: "HD348", status: 0},
    {classId: 6, kidId: "HD099", status: 0},
    {classId: 2, kidId: "HD022", status: 1},
    {classId: 4, kidId: "HD376", status: 4},
    {classId: 4, kidId: "HD045", status: 0},
    {classId: 3, kidId: "HD384", status: 0},
    {classId: 9, kidId: "HD080", status: 0},
    {classId: 2, kidId: "HD278", status: 0},

];

const classInfoTest = [
    {classId: 11, name: "Kitty"},
    {classId: 9, name: "Donald"},
    {classId: 8, name: "Kangaroo"},
    {classId: 6, name: "Lion"},
    {classId: 3, name: "Zebra"},
    {classId: 4, name: "Mickey"},
    {classId: 10, name: "Bear"},
    {classId: 0, name: "Rabbit"},
    {classId: 7, name: "Panda"},
    {classId: 5, name: "Monkey"},
    {classId: 1, name: "Chicken"},
    {classId: 2, name: "Elephant"},
];

const kidInfoTest = [
    {kidId: "HD022", name: "Lê Anh Quân", nickname: undefined},
    {kidId: "HD200", name: "Nguyễn Khôi Nguyên", nickname: undefined},
    {kidId: "HD340", name: "Nguyễn Ngọc Phương  Anh", nickname: undefined},
    {kidId: "HD051", name: "Bùi Trúc Linh", nickname: undefined},
    {kidId: "HD344", name: "Phạm Thanh Trúc", nickname: undefined},
    {kidId: "HD212", name: "Đăng Khoa", nickname: undefined},
    {kidId: "HD463", name: "Nguyễn Gia Hưng", nickname: undefined},
    {kidId: "HD159", name: "Đoàn Thị Hiền Ly", nickname: undefined},
    {kidId: "HD252", name: "Hà Ngân", nickname: undefined},
    {kidId: "HD264", name: "Danh Thái", nickname: undefined},
    {kidId: "HD416", name: "Lê Phạm Huyền  Anh", nickname: undefined},
    {kidId: "HD194", name: "Đỗ Trọng Hiếu", nickname: undefined},
    {kidId: "HD018", name: "Nguyễn Minh Khánh", nickname: undefined},
    {kidId: "HD418", name: "Đỗ Duy Anh", nickname: undefined},
    {kidId: "HD059", name: "Nguyễn Đỗ Tú Anh", nickname: undefined},
    {kidId: "HD132", name: "Nghiêm Hà An", nickname: undefined},
    {kidId: "HD298", name: "Nguyễn Phúc Quảng", nickname: undefined},
    {kidId: "HD150", name: "Nguyễn Đặng Bảo Anh", nickname: undefined},
    {kidId: "HD196", name: "Phạm Kiều Linh", nickname: undefined},
    {kidId: "HD357", name: "Trịnh Minh Thành", nickname: undefined},
    {kidId: "HD435", name: "Trần Đăng Khoa", nickname: undefined},
    {kidId: "HD262", name: "Huy Long", nickname: undefined},
    {kidId: "HD472", name: "Nguyễn Minh Châu", nickname: undefined},
    {kidId: "HD422", name: "Đỗ Đức  Quang", nickname: undefined},
    {kidId: "HD461", name: "Trịnh Gia Bảo", nickname: undefined},
    {kidId: "HD068", name: "Bùi Trần Minh Khang", nickname: undefined},
    {kidId: "HD108", name: "Nguyễn Thiện Nhân", nickname: undefined},
    {kidId: "HD247", name: "Hải Linh", nickname: undefined},
    {kidId: "HD044", name: "Bùi Ngọc Minh Châu", nickname: undefined},
    {kidId: "HD356", name: "Trần Đức Phúc", nickname: undefined},
    {kidId: "HD314", name: "Ngọc  Diệp", nickname: undefined},
    {kidId: "HD171", name: "Lê Ngọc Anh", nickname: undefined},
    {kidId: "HD370", name: "Lê Trâm Anh", nickname: undefined},
    {kidId: "HD042", name: "Nguyễn Nhật Vy", nickname: undefined},
    {kidId: "HD404", name: "Quốc  Anh", nickname: undefined},
    {kidId: "HD373", name: "Gia  Hân", nickname: undefined},
    {kidId: "HD279", name: "Vũ Trọng Khoa", nickname: undefined},
    {kidId: "HD471", name: "Trịnh Lan Hương ", nickname: undefined},
    {kidId: "HD040", name: "Vũ Mai Trang", nickname: undefined},
    {kidId: "HD478", name: "Hữu Khang", nickname: undefined},
    {kidId: "HD115", name: "Vũ Bảo Châu", nickname: undefined},
    {kidId: "HD155", name: "Đoàn Hải Đăng", nickname: undefined},
    {kidId: "HD454", name: "Nguyễn Ngọc  Trung", nickname: undefined},
    {kidId: "HD275", name: "Thanh Bình", nickname: undefined},
    {kidId: "HD328", name: "Hà Minh  Lâm", nickname: undefined},
    {kidId: "HD301", name: "Gia Khánh", nickname: undefined},
    {kidId: "HD010", name: "Nguyễn Hoàng Minh", nickname: undefined},
    {kidId: "HD322", name: "Phan Công Tuấn  Anh", nickname: undefined},
    {kidId: "HD163", name: "Vũ Bảo Ngọc", nickname: undefined},
    {kidId: "HD361", name: "Ngô Quang  Dũng", nickname: undefined},
    {kidId: "HD094", name: "Lê Nguyễn Tùng Anh", nickname: undefined},
    {kidId: "HD148", name: "Đỗ Ngọc Bảo Trâm", nickname: undefined},
    {kidId: "HD182", name: "Lê Thế Sơn", nickname: undefined},
    {kidId: "HD326", name: "Minh  Tuệ", nickname: undefined},
    {kidId: "HD152", name: "Nguyễn Kim Linh Chi", nickname: undefined},
    {kidId: "HD276", name: "Thái Sơn", nickname: undefined},
    {kidId: "HD293", name: "Tú Anh", nickname: undefined},
    {kidId: "HD302", name: "Phạm Nguyễn Uyên Minh", nickname: undefined},
    {kidId: "HD434", name: "Đoàn Minh Nhân", nickname: undefined},
    {kidId: "HD179", name: "Trần Thị Thảo My", nickname: undefined},
    {kidId: "HD184", name: "Nguyễn Quyết Thắng", nickname: undefined},
    {kidId: "HD026", name: "Phạm Nguyễn Hoài An", nickname: undefined},
    {kidId: "HD019", name: "Nguyễn Phương Ngân", nickname: undefined},
    {kidId: "HD234", name: "Nguyễn Bảo Anh", nickname: undefined},
    {kidId: "HD468", name: "Phạm Đức Minh", nickname: undefined},
    {kidId: "HD218", name: "Anh Đức", nickname: undefined},
    {kidId: "HD106", name: "Phí Quang Minh", nickname: undefined},
    {kidId: "HD300", name: "Lý Nhã  Kỳ", nickname: undefined},
    {kidId: "HD274", name: "Viết  Tâm", nickname: undefined},
    {kidId: "HD353", name: "Bảo  Anh", nickname: undefined},
    {kidId: "HD017", name: "Gia Khang", nickname: undefined},
    {kidId: "HD383", name: "Phạm Xuân  Phúc", nickname: undefined},
    {kidId: "HD381", name: "Đình  Cường", nickname: undefined},
    {kidId: "HD341", name: "Nguyễn Quỳnh  Chi", nickname: undefined},
    {kidId: "HD400", name: "Nguyễn Đức  Mạnh", nickname: undefined},
    {kidId: "HD130", name: "Nguyễn Nhã Khánh Vy", nickname: undefined},
    {kidId: "HD408", name: "Phương  Ly", nickname: undefined},
    {kidId: "HD289", name: "Thảo Nguyên", nickname: undefined},
    {kidId: "HD222", name: "Khánh Ngọc", nickname: undefined},
    {kidId: "HD107", name: "Nguyễn Nhật Bảo Nguyên", nickname: undefined},
    {kidId: "HD231", name: "Hải Nam", nickname: undefined},
    {kidId: "HD377", name: "Đỗ Minh  Anh", nickname: undefined},
    {kidId: "HD160", name: "Nguyễn Phạm Duy Nam", nickname: undefined},
    {kidId: "HD330", name: "Tuấn Kiệt", nickname: undefined},
    {kidId: "HD214", name: "Thanh Tùng", nickname: undefined},
    {kidId: "HD475", name: "Đoàn Bảo Lam", nickname: undefined},
    {kidId: "HD267", name: "Tuấn Dũng", nickname: undefined},
    {kidId: "HD266", name: "Trúc Linh", nickname: undefined},
    {kidId: "HD347", name: "Nguyễn Tuấn  Kiệt", nickname: undefined},
    {kidId: "HD049", name: "Phan Bảo Lâm", nickname: undefined},
    {kidId: "HD127", name: "Hà Vũ Thanh Thảo", nickname: undefined},
    {kidId: "HD141", name: "Nguyễn Hải Linh", nickname: undefined},
    {kidId: "HD001", name: "Thùy Chi", nickname: undefined},
    {kidId: "HD030", name: "Nguyễn Khắc An Bảo", nickname: undefined},
    {kidId: "HD329", name: "Trần Hà  Linh", nickname: undefined},
    {kidId: "HD145", name: "Nguyễn Thanh Ngân", nickname: undefined},
    {kidId: "HD140", name: "Lê Cảnh Khang", nickname: undefined},
    {kidId: "HD261", name: "Đình Thiên", nickname: undefined},
    {kidId: "HD359", name: "Nguyễn Linh  Ngọc", nickname: undefined},
    {kidId: "HD008", name: "Nguyễn Tùng Khôi", nickname: undefined},
    {kidId: "HD085", name: "Tô Nhật Tuệ Minh", nickname: undefined},
    {kidId: "HD047", name: "Nguyễn Phạm Duy Hải", nickname: undefined},
    {kidId: "HD067", name: "Ngô Tuấn Khang", nickname: undefined},
    {kidId: "HD052", name: "Nguyễn Nhật Minh", nickname: undefined},
    {kidId: "HD199", name: "Nguyễn Hoàng Nguyên", nickname: undefined},
    {kidId: "HD338", name: "Chu Phạm Nhật Ánh", nickname: undefined},
    {kidId: "HD462", name: "Trịnh Hoài Thu ", nickname: undefined},
    {kidId: "HD333", name: "Nguyễn Nhật  Linh", nickname: undefined},
    {kidId: "HD185", name: "Bùi Minh Trung", nickname: undefined},
    {kidId: "HD161", name: "Nguyễn Linh Nga", nickname: undefined},
    {kidId: "HD151", name: "Dương Minh Ánh", nickname: undefined},
    {kidId: "HD187", name: "Nguyễn Như Việt Anh", nickname: undefined},
    {kidId: "HD360", name: "Lê Gia  Khang", nickname: undefined},
    {kidId: "HD389", name: "Đức  Anh", nickname: undefined},
    {kidId: "HD235", name: "Nhật Minh", nickname: undefined},
    {kidId: "HD124", name: "Mạc Nam Phong", nickname: undefined},
    {kidId: "HD069", name: "Nguyễn Minh Ngọc", nickname: undefined},
    {kidId: "HD287", name: "Phùng An Gia  Minh", nickname: undefined},
    {kidId: "HD013", name: "Nguyễn Minh Anh", nickname: undefined},
    {kidId: "HD216", name: "Minh Quân", nickname: undefined},
    {kidId: "HD384", name: "Tuấn Tú", nickname: undefined},
    {kidId: "HD035", name: "Nhật Minh", nickname: undefined},
    {kidId: "HD004", name: "Nguyễn Phương Ngọc Huyền", nickname: undefined},
    {kidId: "HD415", name: "Đinh Nhật  Minh", nickname: undefined},
    {kidId: "HD241", name: "Việt Anh", nickname: undefined},
    {kidId: "HD112", name: "Phạm Minh Anh", nickname: undefined},
    {kidId: "HD334", name: "Lê Đăng Khôi", nickname: undefined},
    {kidId: "HD406", name: "Đoàn Bảo Lâm", nickname: undefined},
    {kidId: "HD103", name: "Hoàng Tuấn Khôi", nickname: undefined},
    {kidId: "HD158", name: "Nguyễn Tùng Lâm", nickname: undefined},
    {kidId: "HD430", name: "Nguyễn Hải  Anh", nickname: undefined},
    {kidId: "HD024", name: "Phạm Thành Vinh", nickname: undefined},
    {kidId: "HD440", name: "Phí Minh Vũ", nickname: undefined},
    {kidId: "HD036", name: "Lê Cảnh Bình Minh", nickname: undefined},
    {kidId: "HD351", name: "Nguyễn Hữu Nguyên Hoàng", nickname: undefined},
    {kidId: "HD296", name: "Nguyễn Hữu Trí", nickname: undefined},
    {kidId: "HD207", name: "Nguyễn Như Nam Anh", nickname: undefined},
    {kidId: "HD437", name: "Hà Tú Linh", nickname: undefined},
    {kidId: "HD232", name: "Duy Sơn", nickname: undefined},
    {kidId: "HD317", name: "Minh Nhật", nickname: undefined},
    {kidId: "HD425", name: "Ngô Hoài  An", nickname: undefined},
    {kidId: "HD414", name: "Nguyễn Gia Bảo", nickname: undefined},
    {kidId: "HD249", name: "Hà Vũ Minh Châu", nickname: undefined},
    {kidId: "HD128", name: "Vũ Minh Thắng", nickname: undefined},
    {kidId: "HD410", name: "Hà  Quang", nickname: undefined},
    {kidId: "HD426", name: "Tạ Hoàng Minh", nickname: undefined},
    {kidId: "HD007", name: "Nguyễn Hoàng Nhật Khoa", nickname: undefined},
    {kidId: "HD050", name: "Nhật Linh", nickname: undefined},
    {kidId: "HD250", name: "Hoàng Ngân", nickname: undefined},
    {kidId: "HD316", name: "Đăng Quang", nickname: undefined},
    {kidId: "HD307", name: "Chí  Dũng", nickname: undefined},
    {kidId: "HD452", name: "Nguyễn Minh Đăng", nickname: undefined},
    {kidId: "HD470", name: "Nguyễn Trà My", nickname: undefined},
    {kidId: "HD170", name: "Nguyễn Ngọc Châu Anh", nickname: undefined},
    {kidId: "HD176", name: "Ngọc Hân", nickname: undefined},
    {kidId: "HD201", name: "Thúy Quỳnh", nickname: undefined},
    {kidId: "HD197", name: "Khương Hữu Nghĩa", nickname: undefined},
    {kidId: "HD309", name: "Hà Ngân", nickname: undefined},
    {kidId: "HD070", name: "Trần Nguyễn Hải Phong", nickname: undefined},
    {kidId: "HD033", name: "Nguyễn Minh Hùng", nickname: undefined},
    {kidId: "HD310", name: "Huy Long", nickname: undefined},
    {kidId: "HD419", name: "Đức  An", nickname: undefined},
    {kidId: "HD327", name: "Phạm Thùy Dương", nickname: undefined},
    {kidId: "HD087", name: "Đinh Quốc Phi", nickname: undefined},
    {kidId: "HD305", name: "Hà Thư Huyền Châu", nickname: undefined},
    {kidId: "HD088", name: "Nguyễn Dụng Nam Phong", nickname: undefined},
    {kidId: "HD048", name: "Lê Tùng Lâm", nickname: undefined},
    {kidId: "HD335", name: "Hoàng Thùy  Dương", nickname: undefined},
    {kidId: "HD025", name: "Phùng Ngọc Gia An", nickname: undefined},
    {kidId: "HD230", name: "Trần Hoàng Phúc", nickname: undefined},
    {kidId: "HD055", name: "Nguyễn Lê Phi Yến", nickname: undefined},
    {kidId: "HD078", name: "Vũ Ngọc Hà", nickname: undefined},
    {kidId: "HD476", name: "Quản Diệu Hoàng Oanh", nickname: undefined},
    {kidId: "HD420", name: "Lê Nhật Minh  Khang", nickname: undefined},
    {kidId: "HD056", name: "Phan Trần Hà An", nickname: undefined},
    {kidId: "HD037", name: "Phạm Quý Nam", nickname: undefined},
    {kidId: "HD043", name: "Phạm Gia Bảo", nickname: undefined},
    {kidId: "HD226", name: "Huyền Trang", nickname: undefined},
    {kidId: "HD378", name: "Nguyễn Phương Linh", nickname: undefined},
    {kidId: "HD027", name: "Trịnh Hà Anh", nickname: undefined},
    {kidId: "HD198", name: "Phạm Nguyễn Bảo Ngọc", nickname: undefined},
    {kidId: "HD029", name: "Đào Ngọc Ánh", nickname: undefined},
    {kidId: "HD114", name: "Hoàng Quốc Bảo", nickname: undefined},
    {kidId: "HD365", name: "Mè Đức  Anh", nickname: undefined},
    {kidId: "HD467", name: "Nguyễn Hà Bảo Anh ", nickname: undefined},
    {kidId: "HD306", name: "Tăng Thiên Bảo", nickname: undefined},
    {kidId: "HD164", name: "Phạm Hà Bảo Ngọc", nickname: undefined},
    {kidId: "HD093", name: "Nguyễn Minh Thư", nickname: undefined},
    {kidId: "HD369", name: "Trần Khánh  Linh", nickname: undefined},
    {kidId: "HD442", name: "Uyên Nhi", nickname: undefined},
    {kidId: "HD237", name: "Minh Ngọc", nickname: undefined},
    {kidId: "HD284", name: "Nguyễn Đặng Châu Anh", nickname: undefined},
    {kidId: "HD076", name: "Tiến Cường", nickname: undefined},
    {kidId: "HD117", name: "Trần Hải Đăng", nickname: undefined},
    {kidId: "HD398", name: "Trần Kim Hoài An", nickname: undefined},
    {kidId: "HD139", name: "Đỗ Hoàng Hiệp", nickname: undefined},
    {kidId: "HD399", name: "Đỗ Tiến  Dũng", nickname: undefined},
    {kidId: "HD175", name: "Nguyễn Khương Duy", nickname: undefined},
    {kidId: "HD342", name: "Lê Thị Minh  Anh", nickname: undefined},
    {kidId: "HD421", name: "Trần Ngọc Anh  Chi", nickname: undefined},
    {kidId: "HD259", name: "Quang Minh", nickname: undefined},
    {kidId: "HD156", name: "Cao Tiến Đức", nickname: undefined},
    {kidId: "HD119", name: "Trần Trúc Linh", nickname: undefined},
    {kidId: "HD105", name: "Nguyễn Thảo Linh", nickname: undefined},
    {kidId: "HD405", name: "Đào Ngọc  Anh", nickname: undefined},
    {kidId: "HD202", name: "Ong Thảo Tiên", nickname: undefined},
    {kidId: "HD292", name: "Phạm Nguyên Vũ", nickname: undefined},
    {kidId: "HD432", name: "Gia Linh", nickname: undefined},
    {kidId: "HD451", name: "Nguyễn Ngọc Linh ", nickname: undefined},
    {kidId: "HD205", name: "Phạm Mỹ Duyên", nickname: undefined},
    {kidId: "HD439", name: "Đăng Khôi Khôi", nickname: undefined},
    {kidId: "HD441", name: "Ngô Thị Hồng Mai ", nickname: undefined},
    {kidId: "HD358", name: "Hà Tuấn  Minh", nickname: undefined},
    {kidId: "HD144", name: "Nguyễn Thanh Nga", nickname: undefined},
    {kidId: "HD291", name: "Nguyễn Bá Thạch", nickname: undefined},
    {kidId: "HD386", name: "Vũ Đăng  Khoa", nickname: undefined},
    {kidId: "HD272", name: "Lê Huyền  Trang", nickname: undefined},
    {kidId: "HD100", name: "Lê Ngọc Hà", nickname: undefined},
    {kidId: "HD096", name: "Nguyễn Vũ Ngọc Châm", nickname: undefined},
    {kidId: "HD020", name: "Phan Thị Kim Ngân", nickname: undefined},
    {kidId: "HD282", name: "Vũ Kiệt", nickname: undefined},
    {kidId: "HD154", name: "Bùi Huyền Ánh Dương", nickname: undefined},
    {kidId: "HD168", name: "Hồ Anh Tuấn", nickname: undefined},
    {kidId: "HD016", name: "Anh Đức", nickname: undefined},
    {kidId: "HD248", name: "Đỗ Lê Bảo Anh", nickname: undefined},
    {kidId: "HD458", name: "Hà An Ngọc ", nickname: undefined},
    {kidId: "HD379", name: "Hồng  Ngọc", nickname: undefined},
    {kidId: "HD120", name: "Nguyễn Đức Minh", nickname: undefined},
    {kidId: "HD288", name: "Đặng Hoàng Minh  Lâm", nickname: undefined},
    {kidId: "HD101", name: "Ngô Minh Hoàng", nickname: undefined},
    {kidId: "HD116", name: "Phan Nguyễn Thái Dương", nickname: undefined},
    {kidId: "HD303", name: "Thành  Đạt", nickname: undefined},
    {kidId: "HD438", name: "Hà Minh Hưng", nickname: undefined},
    {kidId: "HD138", name: "Phạm Hoàng Dũng", nickname: undefined},
    {kidId: "HD091", name: "Phan Lê Minh Phương", nickname: undefined},
    {kidId: "HD299", name: "Đức  Minh", nickname: undefined},
    {kidId: "HD409", name: "Thảo Nhi", nickname: undefined},
    {kidId: "HD448", name: " Mantra", nickname: undefined},
    {kidId: "HD157", name: "Lê Gia Huy", nickname: undefined},
    {kidId: "HD062", name: "Trần Minh Dũng", nickname: undefined},
    {kidId: "HD375", name: "Nguyễn Ngọc  Anh", nickname: undefined},
    {kidId: "HD113", name: "Nguyễn Quỳnh Anh", nickname: undefined},
    {kidId: "HD394", name: "Phùng Minh Khang", nickname: undefined},
    {kidId: "HD294", name: "Trần Huy Tuấn  Kiệt", nickname: undefined},
    {kidId: "HD045", name: "Nguyễn Trần Phương Chi", nickname: undefined},
    {kidId: "HD129", name: "Đoàn Đức Nguyên Vũ", nickname: undefined},
    {kidId: "HD162", name: "Nguyễn Gia Nghĩa", nickname: undefined},
    {kidId: "HD122", name: "Ngọc Anh", nickname: undefined},
    {kidId: "HD082", name: "Nguyễn Thế Lâm", nickname: undefined},
    {kidId: "HD392", name: "Minh  Đăng", nickname: undefined},
    {kidId: "HD455", name: "Vũ Anh Quân ", nickname: undefined},
    {kidId: "HD111", name: "Lục Bảo Vy", nickname: undefined},
    {kidId: "HD134", name: "Đoàn Minh An", nickname: undefined},
    {kidId: "HD453", name: "Đỗ Huy Hoàng", nickname: undefined},
    {kidId: "HD190", name: "Trần Hữu Đăng", nickname: undefined},
    {kidId: "HD081", name: "Nguyễn Minh Khang", nickname: undefined},
    {kidId: "HD073", name: "Lê Vũ Mộc Trà", nickname: undefined},
    {kidId: "HD447", name: "Phạm Tùng Lâm Lâm", nickname: undefined},
    {kidId: "HD412", name: "Minh  Vy", nickname: undefined},
    {kidId: "HD396", name: "Vũ Đăng  Khôi", nickname: undefined},
    {kidId: "HD387", name: "Quảng  Đức", nickname: undefined},
    {kidId: "HD402", name: "Phạm Hà Bảo Trân", nickname: undefined},
    {kidId: "HD436", name: " Bống", nickname: undefined},
    {kidId: "HD110", name: "Nguyễn Sơn Tùng", nickname: undefined},
    {kidId: "HD271", name: "Gia Bảo", nickname: undefined},
    {kidId: "HD057", name: "Nguyễn Linh An", nickname: undefined},
    {kidId: "HD429", name: "Trần Bảo Vy", nickname: undefined},
    {kidId: "HD349", name: "Tina Tina", nickname: undefined},
    {kidId: "HD382", name: "Phạm Danh Phú", nickname: undefined},
    {kidId: "HD166", name: "Phạm Nguyệt Nhi", nickname: undefined},
    {kidId: "HD079", name: "Đức Hùng", nickname: undefined},
    {kidId: "HD374", name: "Việt  Linh", nickname: undefined},
    {kidId: "HD178", name: "Nguyễn Đinh Huyền My", nickname: undefined},
    {kidId: "HD256", name: "Hoàng Ngân", nickname: undefined},
    {kidId: "HD011", name: "Nguyễn Ngọc Tường Vy", nickname: undefined},
    {kidId: "HD192", name: "Minh Hà", nickname: undefined},
    {kidId: "HD428", name: "Nguyễn Khiết An", nickname: undefined},
    {kidId: "HD355", name: "Hữu  Khang", nickname: undefined},
    {kidId: "HD023", name: "Đặng Ngọc Bảo Quyên", nickname: undefined},
    {kidId: "HD473", name: "Phạm Nguyễn Nhật Minh", nickname: undefined},
    {kidId: "HD065", name: "Cấn Minh Huy", nickname: undefined},
    {kidId: "HD343", name: "Lê Bá  Đức", nickname: undefined},
    {kidId: "HD177", name: "Đoàn Trọng Hiếu", nickname: undefined},
    {kidId: "HD243", name: "Ngọc Thắng", nickname: undefined},
    {kidId: "HD172", name: "Phí Quang Anh", nickname: undefined},
    {kidId: "HD089", name: "Lê Thanh Phong", nickname: undefined},
    {kidId: "HD325", name: "Nguyễn Gia  Khiêm", nickname: undefined},
    {kidId: "HD038", name: "Nguyễn An Nhiên", nickname: undefined},
    {kidId: "HD283", name: "Bảo Linh", nickname: undefined},
    {kidId: "HD099", name: "Đỗ Nguyễn Hải Đăng", nickname: undefined},
    {kidId: "HD084", name: "Hoàng Xuân Mai", nickname: undefined},
    {kidId: "HD071", name: "Lê Hải Phong", nickname: undefined},
    {kidId: "HD362", name: "Vũ Hải Nam", nickname: undefined},
    {kidId: "HD371", name: "Nguyên Vĩnh Kim", nickname: undefined},
    {kidId: "HD388", name: "Lò An Na", nickname: undefined},
    {kidId: "HD308", name: "Nhật  Quang", nickname: undefined},
    {kidId: "HD092", name: "Nguyễn Bá Khánh Toàn", nickname: undefined},
    {kidId: "HD225", name: "Ngân Giang", nickname: undefined},
    {kidId: "HD186", name: "Nguyễn Uy Vũ", nickname: undefined},
    {kidId: "HD240", name: "Bảo Ngọc", nickname: undefined},
    {kidId: "HD242", name: "Việt Dũng", nickname: undefined},
    {kidId: "HD286", name: "Tô Quang Minh", nickname: undefined},
    {kidId: "HD002", name: "Nguyễn Vũ Bách Diệp", nickname: undefined},
    {kidId: "HD469", name: "Phạm Ngọc Huyền", nickname: undefined},
    {kidId: "HD189", name: "Giang Hà Dũng", nickname: undefined},
    {kidId: "HD251", name: "Gia Huy", nickname: undefined},
    {kidId: "HD080", name: "Đặng Hoàng Gia Hưng", nickname: undefined},
    {kidId: "HD054", name: "Hồ Lê Tú Uyên", nickname: undefined},
    {kidId: "HD133", name: "Trần Đào Thiên An", nickname: undefined},
    {kidId: "HD313", name: "Ánh Ngọc", nickname: undefined},
    {kidId: "HD233", name: "Hoàng Dương", nickname: undefined},
    {kidId: "HD297", name: "Kiều Linh", nickname: undefined},
    {kidId: "HD077", name: "Mai Khánh Chi", nickname: undefined},
    {kidId: "HD345", name: "Trương tuệ  Minh", nickname: undefined},
    {kidId: "HD123", name: "Nguyễn Minh Ngọc", nickname: undefined},
    {kidId: "HD320", name: "Tuấn  Long", nickname: undefined},
    {kidId: "HD090", name: "Nguyễn Trường Phúc", nickname: undefined},
    {kidId: "HD269", name: "Minh Hiếu", nickname: undefined},
    {kidId: "HD460", name: "Nguyễn Minh Tuấn ", nickname: undefined},
    {kidId: "HD229", name: "Hà Vi", nickname: undefined},
    {kidId: "HD380", name: "Nguyễn Thiên An", nickname: undefined},
    {kidId: "HD397", name: "Trần Thảo  Nhi", nickname: undefined},
    {kidId: "HD188", name: "Danh Cường", nickname: undefined},
    {kidId: "HD219", name: "Diệp Anh", nickname: undefined},
    {kidId: "HD039", name: "Bùi Đức Quân", nickname: undefined},
    {kidId: "HD464", name: "Lưu Quang Khôi", nickname: undefined},
    {kidId: "HD372", name: "Trần Bình  Minh", nickname: undefined},
    {kidId: "HD195", name: "Vũ Ngọc Khánh", nickname: undefined},
    {kidId: "HD058", name: "Nguyễn Công Hiếu Anh", nickname: undefined},
    {kidId: "HD446", name: "Nguyễn Tuấn Anh ", nickname: undefined},
    {kidId: "HD466", name: "Chu Thạch Tùng", nickname: undefined},
    {kidId: "HD315", name: "Nguyên  Khang", nickname: undefined},
    {kidId: "HD403", name: "Đào Mạnh Duy Khánh", nickname: undefined},
    {kidId: "HD401", name: "Hoàng Thuận Phong", nickname: undefined},
    {kidId: "HD257", name: "Phú Lâm", nickname: undefined},
    {kidId: "HD450", name: "Đặng Gia Hân ", nickname: undefined},
    {kidId: "HD066", name: "Nguyễn Ngọc Quỳnh Hương", nickname: undefined},
    {kidId: "HD003", name: "Vũ Việt Dũng", nickname: undefined},
    {kidId: "HD323", name: "Hương  Nhi", nickname: undefined},
    {kidId: "HD015", name: "Nguyễn Khánh Duy", nickname: undefined},
    {kidId: "HD258", name: "Quỳnh Trang", nickname: undefined},
    {kidId: "HD290", name: "Khánh  An", nickname: undefined},
    {kidId: "HD376", name: "Cao Khánh  Linh", nickname: undefined},
    {kidId: "HD260", name: "Khánh Ly", nickname: undefined},
    {kidId: "HD390", name: "Đức  Bảo", nickname: undefined},
    {kidId: "HD331", name: "Nguyễn San San", nickname: undefined},
    {kidId: "HD006", name: "Hồ Đức Kiên", nickname: undefined},
    {kidId: "HD203", name: "Thanh Thảo", nickname: undefined},
    {kidId: "HD060", name: "Ngọc Bích", nickname: undefined},
    {kidId: "HD350", name: "Minh  Bảo", nickname: undefined},
    {kidId: "HD295", name: "Nhật Quang", nickname: undefined},
    {kidId: "HD245", name: "Anh Thư", nickname: undefined},
    {kidId: "HD368", name: "Vũ Gia  An", nickname: undefined},
    {kidId: "HD227", name: "Trần Vy Yến Trang", nickname: undefined},
    {kidId: "HD220", name: "Trúc Quỳnh", nickname: undefined},
    {kidId: "HD280", name: "Ngô Thanh  Tùng", nickname: undefined},
    {kidId: "HD457", name: "Nguyễn Khôi  Nguyên ", nickname: undefined},
    {kidId: "HD474", name: "Trường Phúc", nickname: undefined},
    {kidId: "HD265", name: "Ánh Dương", nickname: undefined},
    {kidId: "HD236", name: "Vân Khánh", nickname: undefined},
    {kidId: "HD354", name: "Lê Hà  Thành", nickname: undefined},
    {kidId: "HD393", name: "Trần Bảo Kim Ngân", nickname: undefined},
    {kidId: "HD238", name: "Minh Trí", nickname: undefined},
    {kidId: "HD167", name: "Lê Minh Quân", nickname: undefined},
    {kidId: "HD098", name: "Nguyễn Trần Bảo Dương", nickname: undefined},
    {kidId: "HD433", name: "Chu Sơn  Tùng", nickname: undefined},
    {kidId: "HD263", name: "Bảo An", nickname: undefined},
    {kidId: "HD318", name: "Hoàng Bách", nickname: undefined},
    {kidId: "HD324", name: "Triệu Minh  Trung", nickname: undefined},
    {kidId: "HD028", name: "Vũ Đức Anh", nickname: undefined},
    {kidId: "HD444", name: "Nguyễn Quang Hải", nickname: undefined},
    {kidId: "HD104", name: "Nguyễn Phương Linh", nickname: undefined},
    {kidId: "HD465", name: "Nguyễn Minh Khôi", nickname: undefined},
    {kidId: "HD336", name: "Nguyễn Quang  Đăng", nickname: undefined},
    {kidId: "HD191", name: "Minh Đức", nickname: undefined},
    {kidId: "HD174", name: "Đặng Hoài Anh", nickname: undefined},
    {kidId: "HD385", name: "Đinh Công Tuấn  Minh", nickname: undefined},
    {kidId: "HD348", name: "Trần Diễm My", nickname: undefined},
    {kidId: "HD337", name: "Thái An Nhiên", nickname: undefined},
    {kidId: "HD053", name: "Nguyễn Hoàng Khánh My", nickname: undefined},
    {kidId: "HD228", name: "Hoàng Minh", nickname: undefined},
    {kidId: "HD255", name: "Nguyễn Trần Bảo Thiên", nickname: undefined},
    {kidId: "HD173", name: "Nguyễn Đức Quang Anh", nickname: undefined},
    {kidId: "HD180", name: "Nguyễn Anh Quân", nickname: undefined},
    {kidId: "HD118", name: "Nguyễn Hương Giang", nickname: undefined},
    {kidId: "HD459", name: "Cấn Khánh Linh ", nickname: undefined},
    {kidId: "HD109", name: "Nguyễn Đức Tuệ", nickname: undefined},
    {kidId: "HD072", name: "Nguyễn Hữu Phước", nickname: undefined},
    {kidId: "HD304", name: "Trần Nhật Khang", nickname: undefined},
    {kidId: "HD126", name: "Phạm Đức Tài", nickname: undefined},
    {kidId: "HD413", name: "Trân Ngọc Hà", nickname: undefined},
    {kidId: "HD142", name: "Gia Linh", nickname: undefined},
    {kidId: "HD204", name: "Thanh An", nickname: undefined},
    {kidId: "HD014", name: "Vũ Huy Bách", nickname: undefined},
    {kidId: "HD352", name: "Lê Đức  Minh", nickname: undefined},
    {kidId: "HD209", name: "Quỳnh Chi", nickname: undefined},
    {kidId: "HD005", name: "Mai Thu Hương", nickname: undefined},
    {kidId: "HD278", name: "Đỗ Quỳnh Anh", nickname: undefined},
    {kidId: "HD311", name: "Đậu Minh  Hưng", nickname: undefined},
    {kidId: "HD477", name: "Nguyễn Tú Anh", nickname: undefined},
    {kidId: "HD367", name: "Lê Đàm Khánh  Vy", nickname: undefined},
    {kidId: "HD391", name: "Bảo  An", nickname: undefined},
    {kidId: "HD021", name: "Nguyễn Minh Ngọc", nickname: undefined},
    {kidId: "HD102", name: "Đỗ Bảo Khánh", nickname: undefined},
    {kidId: "HD032", name: "Nguyễn Minh Hoàng", nickname: undefined},
    {kidId: "HD456", name: "Lê An Nhiên ", nickname: undefined},
    {kidId: "HD121", name: "Trần Bảo Nam", nickname: undefined},
    {kidId: "HD270", name: "Khánh Vy", nickname: undefined},
    {kidId: "HD364", name: "Nguyễn Nhật  Minh", nickname: undefined},
    {kidId: "HD095", name: "Lê Bảo Anh", nickname: undefined},
    {kidId: "HD281", name: "Gia Khang", nickname: undefined},
    {kidId: "HD064", name: "Mai Ngọc Hân", nickname: undefined},
    {kidId: "HD083", name: "Nguyễn Cao Bảo Linh", nickname: undefined},
    {kidId: "HD143", name: "Đinh Thảo My", nickname: undefined},
    {kidId: "HD366", name: "Lê Tuệ  Lâm", nickname: undefined},
    {kidId: "HD061", name: "Nguyễn Ngọc Diệp", nickname: undefined},
    {kidId: "HD445", name: "Bảo Long", nickname: undefined},
    {kidId: "HD009", name: "Đoàn Tất Bảo Lâm", nickname: undefined},
    {kidId: "HD206", name: "Hương Vy", nickname: undefined},
    {kidId: "HD165", name: "Phan Khôi Nguyên", nickname: undefined},
    {kidId: "HD012", name: "Đặng Châu Anh", nickname: undefined},
    {kidId: "HD146", name: "Đỗ Mai Phương", nickname: undefined},
    {kidId: "HD063", name: "Nguyễn Bảo Hân", nickname: undefined},
    {kidId: "HD417", name: "Nguyễn Ngọc Hà My", nickname: undefined},
    {kidId: "HD213", name: "Đăng Bách", nickname: undefined},
    {kidId: "HD193", name: "Việt Hiếu", nickname: undefined},
    {kidId: "HD346", name: "Ngô Ngọc  Hân", nickname: undefined},
    {kidId: "HD075", name: "Tâm Anh", nickname: undefined},
    {kidId: "HD149", name: "Đặng Bảo Vy", nickname: undefined},
    {kidId: "HD431", name: "Nguyễn Hà  Anh", nickname: undefined},
    {kidId: "HD097", name: "Nguyễn Quỳnh Chi", nickname: undefined},
    {kidId: "HD277", name: "Gia Khánh", nickname: undefined},
    {kidId: "HD244", name: "Nguyễn Đình Bảo Khang", nickname: undefined},
    {kidId: "HD443", name: "Phạm Diệu An", nickname: undefined},
    {kidId: "HD423", name: "Cấn Khánh Chi", nickname: undefined},
    {kidId: "HD169", name: "Lê Hoàng Yến", nickname: undefined},
    {kidId: "HD332", name: "Nguyễn Hoàng Yến Nhi", nickname: undefined},
    {kidId: "HD273", name: "Cảnh Duy", nickname: undefined},
    {kidId: "HD407", name: "Lê Minh Thư", nickname: undefined},
    {kidId: "HD074", name: "Lê Phạm Bảo Anh", nickname: undefined},
    {kidId: "HD147", name: "Nguyễn Đình Hoàng Sơn", nickname: undefined},
    {kidId: "HD136", name: "Vũ Đức Anh", nickname: undefined},
    {kidId: "HD424", name: "Lương Đào Quỳnh Anh", nickname: undefined},
    {kidId: "HD339", name: "Lê Phạm Nhã Uyên", nickname: undefined},
    {kidId: "HD411", name: "Tạ Minh Quang", nickname: undefined},
    {kidId: "HD031", name: "Nguyễn Minh Châu", nickname: undefined},
    {kidId: "HD395", name: "Vũ Huyền  Trang", nickname: undefined},
    {kidId: "HD137", name: "Đoàn Quỳnh Chi", nickname: undefined},
    {kidId: "HD363", name: "Phùng Viết  Thành", nickname: undefined},
    {kidId: "HD208", name: "Yến Vy", nickname: undefined},
    {kidId: "HD285", name: "Ngọc Hà", nickname: undefined},
    {kidId: "HD131", name: "Nguyễn Đoàn Khánh Vy", nickname: undefined},
    {kidId: "HD321", name: "Hạ Vy", nickname: undefined},
    {kidId: "HD046", name: "Trần Diệp Chi", nickname: undefined},
    {kidId: "HD449", name: "Chử Khôi Nguyên", nickname: undefined},
    {kidId: "HD319", name: "Phạm  Trường", nickname: undefined},
    {kidId: "HD153", name: "Lê Trung Dũng", nickname: undefined},
    {kidId: "HD210", name: "Bảo An", nickname: undefined},
    {kidId: "HD312", name: "Quỳnh Nhi", nickname: undefined},
    {kidId: "HD427", name: "Tạ Hoàng Minh Khang", nickname: undefined},

]

export { kidStatusTest, kidInfoTest, classInfoTest }