// const kidStatusTest = [
//     {classId: 0, kidId: "HD501", status: 0},
//     {classId: 0, kidId: "HD436", status: 0},
//     {classId: 0, kidId: "HD420", status: 0},
//     {classId: 0, kidId: "HD502", status: 0},
//     {classId: 0, kidId: "HD003", status: 0},
//     {classId: 0, kidId: "HD463", status: 0},
//     {classId: 0, kidId: "HD418", status: 0},
//     {classId: 0, kidId: "HD441", status: 0},
//     {classId: 0, kidId: "HD435", status: 0},
//     {classId: 0, kidId: "HD419", status: 0},
//     {classId: 0, kidId: "HD317", status: 0},
//     {classId: 0, kidId: "HD387", status: 0},
//     {classId: 0, kidId: "HD489", status: 0},
//     {classId: 0, kidId: "HD008", status: 0},
//     {classId: 0, kidId: "HD496", status: 0},
//     {classId: 0, kidId: "HD363", status: 0},
//     {classId: 0, kidId: "HD459", status: 0},
//     {classId: 0, kidId: "HD208", status: 0},
//     {classId: 0, kidId: "HD346", status: 0},
//     {classId: 0, kidId: "HD349", status: 0},
//     {classId: 0, kidId: "HD477", status: 0},
//     {classId: 0, kidId: "HD411", status: 0},
//     {classId: 0, kidId: "HD494", status: 0},
//     {classId: 0, kidId: "HD212", status: 0},
//     {classId: 0, kidId: "HD444", status: 0},
//     {classId: 0, kidId: "HD213", status: 0},
//     {classId: 0, kidId: "HD315", status: 0},
//     {classId: 0, kidId: "HD338", status: 0},
//     {classId: 0, kidId: "HD497", status: 0},
//     {classId: 0, kidId: "HD453", status: 0},
//     {classId: 0, kidId: "HD454", status: 0},
//     {classId: 0, kidId: "HD355", status: 0},
//     {classId: 0, kidId: "HD465", status: 0},
//     {classId: 0, kidId: "HD404", status: 0},
//     {classId: 1, kidId: "HD415", status: 0},
//     {classId: 1, kidId: "HD357", status: 0},
//     {classId: 1, kidId: "HD446", status: 0},
//     {classId: 1, kidId: "HD473", status: 0},
//     {classId: 1, kidId: "HD380", status: 0},
//     {classId: 1, kidId: "HD392", status: 0},
//     {classId: 1, kidId: "HD403", status: 0},
//     {classId: 1, kidId: "HD020", status: 0},
//     {classId: 1, kidId: "HD300", status: 0},
//     {classId: 1, kidId: "HD498", status: 0},
//     {classId: 1, kidId: "HD014", status: 0},
//     {classId: 1, kidId: "HD281", status: 0},
//     {classId: 1, kidId: "HD412", status: 0},
//     {classId: 1, kidId: "HD431", status: 0},
//     {classId: 1, kidId: "HD291", status: 0},
//     {classId: 1, kidId: "HD460", status: 0},
//     {classId: 1, kidId: "HD386", status: 0},
//     {classId: 1, kidId: "HD407", status: 0},
//     {classId: 1, kidId: "HD461", status: 0},
//     {classId: 1, kidId: "HD400", status: 0},
//     {classId: 1, kidId: "HD011", status: 0},
//     {classId: 1, kidId: "HD023", status: 0},
//     {classId: 1, kidId: "HD345", status: 0},
//     {classId: 1, kidId: "HD366", status: 0},
//     {classId: 1, kidId: "HD451", status: 0},
//     {classId: 1, kidId: "HD370", status: 0},
//     {classId: 1, kidId: "HD445", status: 0},
//     {classId: 1, kidId: "HD471", status: 0},
//     {classId: 1, kidId: "HD373", status: 0},
//     {classId: 1, kidId: "HD290", status: 0},
//     {classId: 1, kidId: "HD324", status: 0},
//     {classId: 1, kidId: "HD009", status: 0},
//     {classId: 1, kidId: "HD450", status: 0},
//     {classId: 1, kidId: "HD430", status: 0},
//     {classId: 1, kidId: "HD318", status: 0},
//     {classId: 1, kidId: "HD443", status: 0},
//     {classId: 2, kidId: "HD492", status: 0},
//     {classId: 2, kidId: "HD467", status: 0},
//     {classId: 2, kidId: "HD470", status: 0},
//     {classId: 2, kidId: "HD478", status: 0},
//     {classId: 2, kidId: "HD416", status: 0},
//     {classId: 2, kidId: "HD406", status: 0},
//     {classId: 2, kidId: "HD051", status: 0},
//     {classId: 2, kidId: "HD448", status: 0},
//     {classId: 2, kidId: "HD054", status: 0},
//     {classId: 2, kidId: "HD490", status: 0},
//     {classId: 2, kidId: "HD405", status: 0},
//     {classId: 2, kidId: "HD335", status: 0},
//     {classId: 2, kidId: "HD385", status: 0},
//     {classId: 2, kidId: "HD417", status: 0},
//     {classId: 2, kidId: "HD432", status: 0},
//     {classId: 2, kidId: "HD457", status: 0},
//     {classId: 2, kidId: "HD408", status: 0},
//     {classId: 2, kidId: "HD358", status: 0},
//     {classId: 2, kidId: "HD007", status: 0},
//     {classId: 2, kidId: "HD048", status: 0},
//     {classId: 2, kidId: "HD361", status: 0},
//     {classId: 2, kidId: "HD022", status: 0},
//     {classId: 2, kidId: "HD458", status: 0},
//     {classId: 2, kidId: "HD371", status: 0},
//     {classId: 2, kidId: "HD044", status: 0},
//     {classId: 2, kidId: "HD428", status: 0},
//     {classId: 2, kidId: "HD447", status: 0},
//     {classId: 2, kidId: "HD295", status: 0},
//     {classId: 2, kidId: "HD493", status: 0},
//     {classId: 2, kidId: "HD378", status: 0},
//     {classId: 2, kidId: "HD301", status: 0},
//     {classId: 2, kidId: "HD344", status: 0},
//     {classId: 2, kidId: "HD047", status: 0},
//     {classId: 2, kidId: "HD424", status: 0},
//     {classId: 2, kidId: "HD438", status: 0},
//     {classId: 2, kidId: "HD353", status: 0},
//     {classId: 2, kidId: "HD433", status: 0},
//     {classId: 2, kidId: "HD207", status: 0},
//     {classId: 2, kidId: "HD475", status: 0},
//     {classId: 2, kidId: "HD476", status: 0},
//     {classId: 2, kidId: "HD360", status: 0},
//     {classId: 2, kidId: "HD214", status: 0},
//     {classId: 2, kidId: "HD394", status: 0},
//     {classId: 2, kidId: "HD377", status: 0},
//     {classId: 2, kidId: "HD347", status: 0},
//     {classId: 3, kidId: "HD193", status: 0},
//     {classId: 3, kidId: "HD294", status: 0},
//     {classId: 3, kidId: "HD046", status: 0},
//     {classId: 3, kidId: "HD474", status: 0},
//     {classId: 3, kidId: "HD343", status: 0},
//     {classId: 3, kidId: "HD180", status: 0},
//     {classId: 3, kidId: "HD401", status: 0},
//     {classId: 3, kidId: "HD172", status: 0},
//     {classId: 3, kidId: "HD368", status: 0},
//     {classId: 3, kidId: "HD053", status: 0},
//     {classId: 3, kidId: "HD423", status: 0},
//     {classId: 3, kidId: "HD384", status: 0},
//     {classId: 3, kidId: "HD319", status: 0},
//     {classId: 3, kidId: "HD006", status: 0},
//     {classId: 3, kidId: "HD399", status: 0},
//     {classId: 3, kidId: "HD367", status: 0},
//     {classId: 3, kidId: "HD425", status: 0},
//     {classId: 3, kidId: "HD365", status: 0},
//     {classId: 3, kidId: "HD005", status: 0},
//     {classId: 3, kidId: "HD439", status: 0},
//     {classId: 3, kidId: "HD284", status: 0},
//     {classId: 3, kidId: "HD210", status: 0},
//     {classId: 3, kidId: "HD024", status: 0},
//     {classId: 3, kidId: "HD469", status: 0},
//     {classId: 3, kidId: "HD188", status: 0},
//     {classId: 3, kidId: "HD468", status: 0},
//     {classId: 3, kidId: "HD336", status: 0},
//     {classId: 3, kidId: "HD316", status: 0},
//     {classId: 3, kidId: "HD375", status: 0},
//     {classId: 3, kidId: "HD016", status: 0},
//     {classId: 3, kidId: "HD352", status: 0},
//     {classId: 3, kidId: "HD206", status: 0},
//     {classId: 3, kidId: "HD337", status: 0},
//     {classId: 3, kidId: "HD314", status: 0},
//     {classId: 3, kidId: "HD398", status: 0},
//     {classId: 3, kidId: "HD307", status: 0},
//     {classId: 3, kidId: "HD299", status: 0},
//     {classId: 3, kidId: "HD422", status: 0},
//     {classId: 3, kidId: "HD191", status: 0},
//     {classId: 4, kidId: "HD126", status: 0},
//     {classId: 4, kidId: "HD350", status: 0},
//     {classId: 4, kidId: "HD216", status: 0},
//     {classId: 4, kidId: "HD116", status: 0},
//     {classId: 4, kidId: "HD402", status: 0},
//     {classId: 4, kidId: "HD466", status: 0},
//     {classId: 4, kidId: "HD369", status: 0},
//     {classId: 4, kidId: "HD001", status: 0},
//     {classId: 4, kidId: "HD293", status: 0},
//     {classId: 4, kidId: "HD410", status: 0},
//     {classId: 4, kidId: "HD287", status: 0},
//     {classId: 4, kidId: "HD119", status: 0},
//     {classId: 4, kidId: "HD356", status: 0},
//     {classId: 4, kidId: "HD285", status: 0},
//     {classId: 4, kidId: "HD297", status: 0},
//     {classId: 4, kidId: "HD393", status: 0},
//     {classId: 4, kidId: "HD010", status: 0},
//     {classId: 4, kidId: "HD409", status: 0},
//     {classId: 4, kidId: "HD280", status: 0},
//     {classId: 4, kidId: "HD129", status: 0},
//     {classId: 4, kidId: "HD286", status: 0},
//     {classId: 4, kidId: "HD372", status: 0},
//     {classId: 4, kidId: "HD464", status: 0},
//     {classId: 4, kidId: "HD052", status: 0},
//     {classId: 4, kidId: "HD279", status: 0},
//     {classId: 4, kidId: "HD455", status: 0},
//     {classId: 4, kidId: "HD192", status: 0},
//     {classId: 4, kidId: "HD278", status: 0},
//     {classId: 4, kidId: "HD326", status: 0},
//     {classId: 4, kidId: "HD328", status: 0},
//     {classId: 4, kidId: "HD414", status: 0},
//     {classId: 4, kidId: "HD112", status: 0},
//     {classId: 4, kidId: "HD397", status: 0},
//     {classId: 4, kidId: "HD348", status: 0},
//     {classId: 4, kidId: "HD503", status: 0},
//     {classId: 4, kidId: "HD379", status: 0},
//     {classId: 4, kidId: "HD128", status: 0},
//     {classId: 4, kidId: "HD396", status: 0},
//     {classId: 4, kidId: "HD364", status: 0},
//     {classId: 4, kidId: "HD429", status: 0},
//     {classId: 4, kidId: "HD472", status: 0},
//     {classId: 4, kidId: "HD118", status: 0},
//     {classId: 4, kidId: "HD120", status: 0},
//     {classId: 4, kidId: "HD288", status: 0},
//     {classId: 4, kidId: "HD334", status: 0},
//     {classId: 4, kidId: "HD376", status: 0},
//     {classId: 4, kidId: "HD220", status: 0},
//     {classId: 5, kidId: "HD055", status: 0},
//     {classId: 5, kidId: "HD197", status: 0},
//     {classId: 5, kidId: "HD382", status: 0},
//     {classId: 5, kidId: "HD136", status: 0},
//     {classId: 5, kidId: "HD200", status: 0},
//     {classId: 5, kidId: "HD013", status: 0},
//     {classId: 5, kidId: "HD304", status: 0},
//     {classId: 5, kidId: "HD201", status: 0},
//     {classId: 5, kidId: "HD219", status: 0},
//     {classId: 5, kidId: "HD130", status: 0},
//     {classId: 5, kidId: "HD050", status: 0},
//     {classId: 5, kidId: "HD017", status: 0},
//     {classId: 5, kidId: "HD325", status: 0},
//     {classId: 5, kidId: "HD303", status: 0},
//     {classId: 5, kidId: "HD491", status: 0},
//     {classId: 5, kidId: "HD190", status: 0},
//     {classId: 5, kidId: "HD147", status: 0},
//     {classId: 5, kidId: "HD004", status: 0},
//     {classId: 5, kidId: "HD462", status: 0},
//     {classId: 5, kidId: "HD310", status: 0},
//     {classId: 5, kidId: "HD138", status: 0},
//     {classId: 5, kidId: "HD495", status: 0},
//     {classId: 5, kidId: "HD218", status: 0},
//     {classId: 5, kidId: "HD339", status: 0},
//     {classId: 5, kidId: "HD139", status: 0},
//     {classId: 5, kidId: "HD359", status: 0},
//     {classId: 5, kidId: "HD327", status: 0},
//     {classId: 5, kidId: "HD021", status: 0},
//     {classId: 5, kidId: "HD202", status: 0},
//     {classId: 5, kidId: "HD140", status: 0},
//     {classId: 5, kidId: "HD018", status: 0},
//     {classId: 5, kidId: "HD198", status: 0},
//     {classId: 5, kidId: "HD209", status: 0},
//     {classId: 5, kidId: "HD015", status: 0},
//     {classId: 5, kidId: "HD145", status: 0},
//     {classId: 5, kidId: "HD019", status: 0},
//     {classId: 5, kidId: "HD306", status: 0},
//     {classId: 5, kidId: "HD142", status: 0},
//     {classId: 5, kidId: "HD187", status: 0},
//     {classId: 5, kidId: "HD205", status: 0},
//     {classId: 5, kidId: "HD132", status: 0},
//     {classId: 6, kidId: "HD039", status: 0},
//     {classId: 6, kidId: "HD043", status: 0},
//     {classId: 6, kidId: "HD111", status: 0},
//     {classId: 6, kidId: "HD149", status: 0},
//     {classId: 6, kidId: "HD274", status: 0},
//     {classId: 6, kidId: "HD449", status: 0},
//     {classId: 6, kidId: "HD124", status: 0},
//     {classId: 6, kidId: "HD144", status: 0},
//     {classId: 6, kidId: "HD025", status: 0},
//     {classId: 6, kidId: "HD099", status: 0},
//     {classId: 6, kidId: "HD342", status: 0},
//     {classId: 6, kidId: "HD134", status: 0},
//     {classId: 6, kidId: "HD452", status: 0},
//     {classId: 6, kidId: "HD227", status: 0},
//     {classId: 6, kidId: "HD002", status: 0},
//     {classId: 6, kidId: "HD109", status: 0},
//     {classId: 6, kidId: "HD103", status: 0},
//     {classId: 6, kidId: "HD097", status: 0},
//     {classId: 6, kidId: "HD122", status: 0},
//     {classId: 6, kidId: "HD437", status: 0},
//     {classId: 6, kidId: "HD302", status: 0},
//     {classId: 6, kidId: "HD231", status: 0},
//     {classId: 6, kidId: "HD311", status: 0},
//     {classId: 6, kidId: "HD049", status: 0},
//     {classId: 6, kidId: "HD036", status: 0},
//     {classId: 6, kidId: "HD038", status: 0},
//     {classId: 6, kidId: "HD374", status: 0},
//     {classId: 6, kidId: "HD133", status: 0},
//     {classId: 6, kidId: "HD146", status: 0},
//     {classId: 6, kidId: "HD113", status: 0},
//     {classId: 6, kidId: "HD226", status: 0},
//     {classId: 6, kidId: "HD117", status: 0},
//     {classId: 6, kidId: "HD225", status: 0},
//     {classId: 6, kidId: "HD115", status: 0},
//     {classId: 6, kidId: "HD045", status: 0},
//     {classId: 6, kidId: "HD137", status: 0},
//     {classId: 6, kidId: "HD141", status: 0},
//     {classId: 6, kidId: "HD381", status: 0},
//     {classId: 6, kidId: "HD143", status: 0},
//     {classId: 6, kidId: "HD030", status: 0},
//     {classId: 6, kidId: "HD148", status: 0},
//     {classId: 6, kidId: "HD233", status: 0},
//     {classId: 7, kidId: "HD040", status: 0},
//     {classId: 7, kidId: "HD121", status: 0},
//     {classId: 7, kidId: "HD235", status: 0},
//     {classId: 7, kidId: "HD073", status: 0},
//     {classId: 7, kidId: "HD170", status: 0},
//     {classId: 7, kidId: "HD456", status: 0},
//     {classId: 7, kidId: "HD237", status: 0},
//     {classId: 7, kidId: "HD131", status: 0},
//     {classId: 7, kidId: "HD322", status: 0},
//     {classId: 7, kidId: "HD060", status: 0},
//     {classId: 7, kidId: "HD236", status: 0},
//     {classId: 7, kidId: "HD395", status: 0},
//     {classId: 7, kidId: "HD067", status: 0},
//     {classId: 7, kidId: "HD070", status: 0},
//     {classId: 7, kidId: "HD442", status: 0},
//     {classId: 7, kidId: "HD389", status: 0},
//     {classId: 7, kidId: "HD061", status: 0},
//     {classId: 7, kidId: "HD362", status: 0},
//     {classId: 7, kidId: "HD230", status: 0},
//     {classId: 7, kidId: "HD182", status: 0},
//     {classId: 7, kidId: "HD100", status: 0},
//     {classId: 7, kidId: "HD175", status: 0},
//     {classId: 7, kidId: "HD333", status: 0},
//     {classId: 7, kidId: "HD312", status: 0},
//     {classId: 7, kidId: "HD434", status: 0},
//     {classId: 7, kidId: "HD184", status: 0},
//     {classId: 7, kidId: "HD427", status: 0},
//     {classId: 7, kidId: "HD185", status: 0},
//     {classId: 7, kidId: "HD390", status: 0},
//     {classId: 7, kidId: "HD186", status: 0},
//     {classId: 7, kidId: "HD057", status: 0},
//     {classId: 7, kidId: "HD340", status: 0},
//     {classId: 7, kidId: "HD421", status: 0},
//     {classId: 7, kidId: "HD332", status: 0},
//     {classId: 7, kidId: "HD354", status: 0},
//     {classId: 7, kidId: "HD500", status: 0},
//     {classId: 7, kidId: "HD277", status: 0},
//     {classId: 7, kidId: "HD114", status: 0},
//     {classId: 7, kidId: "HD289", status: 0},
//     {classId: 7, kidId: "HD204", status: 0},
//     {classId: 7, kidId: "HD341", status: 0},
//     {classId: 7, kidId: "HD066", status: 0},
//     {classId: 8, kidId: "HD266", status: 0},
//     {classId: 8, kidId: "HD101", status: 0},
//     {classId: 8, kidId: "HD222", status: 0},
//     {classId: 8, kidId: "HD042", status: 0},
//     {classId: 8, kidId: "HD256", status: 0},
//     {classId: 8, kidId: "HD229", status: 0},
//     {classId: 8, kidId: "HD158", status: 0},
//     {classId: 8, kidId: "HD098", status: 0},
//     {classId: 8, kidId: "HD309", status: 0},
//     {classId: 8, kidId: "HD108", status: 0},
//     {classId: 8, kidId: "HD095", status: 0},
//     {classId: 8, kidId: "HD264", status: 0},
//     {classId: 8, kidId: "HD094", status: 0},
//     {classId: 8, kidId: "HD323", status: 0},
//     {classId: 8, kidId: "HD029", status: 0},
//     {classId: 8, kidId: "HD440", status: 0},
//     {classId: 8, kidId: "HD255", status: 0},
//     {classId: 8, kidId: "HD313", status: 0},
//     {classId: 8, kidId: "HD096", status: 0},
//     {classId: 8, kidId: "HD151", status: 0},
//     {classId: 8, kidId: "HD262", status: 0},
//     {classId: 8, kidId: "HD031", status: 0},
//     {classId: 8, kidId: "HD123", status: 0},
//     {classId: 8, kidId: "HD027", status: 0},
//     {classId: 8, kidId: "HD248", status: 0},
//     {classId: 8, kidId: "HD271", status: 0},
//     {classId: 8, kidId: "HD152", status: 0},
//     {classId: 8, kidId: "HD104", status: 0},
//     {classId: 8, kidId: "HD351", status: 0},
//     {classId: 8, kidId: "HD168", status: 0},
//     {classId: 8, kidId: "HD163", status: 0},
//     {classId: 8, kidId: "HD261", status: 0},
//     {classId: 8, kidId: "HD159", status: 0},
//     {classId: 8, kidId: "HD164", status: 0},
//     {classId: 8, kidId: "HD165", status: 0},
//     {classId: 8, kidId: "HD330", status: 0},
//     {classId: 8, kidId: "HD267", status: 0},
//     {classId: 8, kidId: "HD258", status: 0},
//     {classId: 8, kidId: "HD028", status: 0},
//     {classId: 8, kidId: "HD296", status: 0},
//     {classId: 8, kidId: "HD270", status: 0},
//     {classId: 8, kidId: "HD167", status: 0},
//     {classId: 8, kidId: "HD110", status: 0},
//     {classId: 8, kidId: "HD033", status: 0},
//     {classId: 8, kidId: "HD259", status: 0},
//     {classId: 8, kidId: "HD169", status: 0},
//     {classId: 8, kidId: "HD102", status: 0},
//     {classId: 8, kidId: "HD257", status: 0},
//     {classId: 8, kidId: "HD298", status: 0},
//     {classId: 8, kidId: "HD232", status: 0},
//     {classId: 8, kidId: "HD166", status: 0},
//     {classId: 8, kidId: "HD260", status: 0},
//     {classId: 8, kidId: "HD263", status: 0},
//     {classId: 8, kidId: "HD269", status: 0},
//     {classId: 8, kidId: "HD106", status: 0},
//     {classId: 8, kidId: "HD265", status: 0},
//     {classId: 8, kidId: "HD276", status: 0},
//     {classId: 8, kidId: "HD153", status: 0},
//     {classId: 8, kidId: "HD092", status: 0},
//     {classId: 8, kidId: "HD499", status: 0},
//     {classId: 8, kidId: "HD228", status: 0},
//     {classId: 8, kidId: "HD292", status: 0},
//     {classId: 8, kidId: "HD329", status: 0},
//     {classId: 8, kidId: "HD331", status: 0},
//     {classId: 9, kidId: "HD242", status: 0},
//     {classId: 9, kidId: "HD283", status: 0},
//     {classId: 9, kidId: "HD088", status: 0},
//     {classId: 9, kidId: "HD077", status: 0},
//     {classId: 9, kidId: "HD160", status: 0},
//     {classId: 9, kidId: "HD383", status: 0},
//     {classId: 9, kidId: "HD069", status: 0},
//     {classId: 9, kidId: "HD026", status: 0},
//     {classId: 9, kidId: "HD150", status: 0},
//     {classId: 9, kidId: "HD059", status: 0},
//     {classId: 9, kidId: "HD195", status: 0},
//     {classId: 9, kidId: "HD062", status: 0},
//     {classId: 9, kidId: "HD035", status: 0},
//     {classId: 9, kidId: "HD037", status: 0},
//     {classId: 9, kidId: "HD251", status: 0},
//     {classId: 9, kidId: "HD032", status: 0},
//     {classId: 9, kidId: "HD388", status: 0},
//     {classId: 9, kidId: "HD238", status: 0},
//     {classId: 9, kidId: "HD072", status: 0},
//     {classId: 9, kidId: "HD154", status: 0},
//     {classId: 9, kidId: "HD083", status: 0},
//     {classId: 9, kidId: "HD162", status: 0},
//     {classId: 9, kidId: "HD091", status: 0},
//     {classId: 9, kidId: "HD079", status: 0},
//     {classId: 9, kidId: "HD058", status: 0},
//     {classId: 9, kidId: "HD064", status: 0},
//     {classId: 9, kidId: "HD161", status: 0},
//     {classId: 9, kidId: "HD157", status: 0},
//     {classId: 9, kidId: "HD249", status: 0},
//     {classId: 9, kidId: "HD065", status: 0},
//     {classId: 9, kidId: "HD087", status: 0},
//     {classId: 9, kidId: "HD273", status: 0},
//     {classId: 9, kidId: "HD078", status: 0},
//     {classId: 9, kidId: "HD282", status: 0},
//     {classId: 9, kidId: "HD245", status: 0},
//     {classId: 9, kidId: "HD250", status: 0},
//     {classId: 9, kidId: "HD085", status: 0},
//     {classId: 9, kidId: "HD075", status: 0},
//     {classId: 9, kidId: "HD426", status: 0},
//     {classId: 9, kidId: "HD071", status: 0},
//     {classId: 9, kidId: "HD320", status: 0},
//     {classId: 9, kidId: "HD056", status: 0},
//     {classId: 9, kidId: "HD127", status: 0},
//     {classId: 9, kidId: "HD089", status: 0},
//     {classId: 9, kidId: "HD156", status: 0},
//     {classId: 9, kidId: "HD090", status: 0},
//     {classId: 9, kidId: "HD155", status: 0},
//     {classId: 9, kidId: "HD247", status: 0},
//     {classId: 9, kidId: "HD391", status: 0},
//     {classId: 9, kidId: "HD080", status: 0},
//     {classId: 9, kidId: "HD063", status: 0},
//     {classId: 9, kidId: "HD068", status: 0},
//     {classId: 9, kidId: "HD196", status: 0},
//     {classId: 9, kidId: "HD105", status: 0},
//     {classId: 9, kidId: "HD081", status: 0},
//     {classId: 9, kidId: "HD240", status: 0},
//     {classId: 9, kidId: "HD074", status: 0},
//     {classId: 9, kidId: "HD243", status: 0},
//     {classId: 9, kidId: "HD093", status: 0},
//     {classId: 9, kidId: "HD234", status: 0},
//     {classId: 9, kidId: "HD272", status: 0},
//     {classId: 9, kidId: "HD252", status: 0},
//     {classId: 9, kidId: "HD107", status: 0},
//     {classId: 9, kidId: "HD308", status: 0},
//     {classId: 9, kidId: "HD084", status: 0},
//     {classId: 9, kidId: "HD076", status: 0},
//     {classId: 9, kidId: "HD241", status: 0},
//     {classId: 9, kidId: "HD413", status: 0},
//     {classId: 9, kidId: "HD082", status: 0},
//     {classId: 9, kidId: "HD244", status: 0},
//     {classId: 10, kidId: "HD177", status: 0},
//     {classId: 10, kidId: "HD275", status: 0},
//     {classId: 10, kidId: "HD178", status: 0},
//     {classId: 10, kidId: "HD171", status: 0},
//     {classId: 10, kidId: "HD176", status: 0},
//     {classId: 10, kidId: "HD173", status: 0},
//     {classId: 10, kidId: "HD179", status: 0},
//     {classId: 10, kidId: "HD174", status: 0},
//     {classId: 10, kidId: "HD305", status: 0},
//     {classId: 10, kidId: "HD321", status: 0},
//     {classId: 11, kidId: "HD194", status: 0},
//     {classId: 11, kidId: "HD189", status: 0},
//     {classId: 11, kidId: "HD199", status: 0},
//     {classId: 11, kidId: "HD203", status: 0},
//     {classId: 11, kidId: "HD012", status: 0},

// ];

const classInfoTest = [
    {classId: 0, name: "Rabbit", total: 31},
    {classId: 1, name: "Chicken", total: 41},
    {classId: 2, name: "Elephant", total: 46},
    {classId: 3, name: "Zebra", total: 38},
    {classId: 4, name: "Mickey", total: 48},
    {classId: 5, name: "Monkey", total: 35},
    {classId: 6, name: "Lion", total: 36},
    {classId: 7, name: "Panda", total: 40},
    {classId: 8, name: "Kangaroo", total: 63},
    {classId: 9, name: "Donald", total: 67},
    {classId: 10, name: "Bear", total: 10},
    {classId: 11, name: "Kitty", total: 5},
];

const kidInfoTest = [
    {kidId: "HD494", name: "Lê Đình Tùng  Lâm ", nickname: "Tôm", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD376", name: "Cao Khánh  Linh", nickname: "", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD446", name: "Nguyễn Tuấn Anh ", nickname: "Bo", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD024", name: "Phạm Thành Vinh", nickname: "", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD401", name: "Hoàng Thuận Phong", nickname: "Win", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD019", name: "Nguyễn Phương Ngân", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD470", name: "Nguyễn Trà My", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD141", name: "Nguyễn Hải Linh", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD029", name: "Đào Ngọc Ánh", nickname: "", classId: 8, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD389", name: "Phạm Đức  Anh", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD184", name: "Nguyễn Quyết Thắng", nickname: "Bi", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD121", name: "Trần Bảo Nam", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD302", name: "Phạm Nguyễn Uyên Minh", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD476", name: "Quản  Hoàng Oanh", nickname: "Nhím", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD478", name: "Nguyễn Hữu Khang", nickname: "Zôn", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD327", name: "Phạm Thùy Dương", nickname: "Bống", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD146", name: "Đỗ Mai Phương", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD219", name: "Diệp Anh", nickname: "Xuka", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD175", name: "Nguyễn Khương Duy", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD049", name: "Phan Bảo Lâm", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD055", name: "Nguyễn Lê Phi Yến", nickname: "Dâu Tây", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD471", name: "Trịnh Lan Hương ", nickname: "nghé", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD368", name: "Vũ Gia  An", nickname: "Bông Xù", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD363", name: "Phùng Viết  Thành", nickname: "gạo", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD127", name: "Hà Vũ Thanh Thảo", nickname: "", classId: 9, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD423", name: "Cấn Khánh Chi", nickname: "kem", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD358", name: "Hà Tuấn  Minh", nickname: "Bon", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD406", name: "Đoàn Bảo Lâm", nickname: "Bon", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD131", name: "Nguyễn Đoàn Khánh Vy", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD474", name: "Trường Phúc", nickname: "Mốc", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD278", name: "Đỗ Quỳnh Anh", nickname: "Thỏ", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD373", name: "Gia Hân", nickname: "sóc", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD031", name: "Nguyễn Minh Châu", nickname: "", classId: 8, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD385", name: "Đinh Công Tuấn  Minh", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD028", name: "Vũ Đức Anh", nickname: "", classId: 8, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD130", name: "Nguyễn Nhã Khánh Vy", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD398", name: "Trần Kim Hoài An", nickname: "", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD497", name: "Lê Nhật Minh  Khang", nickname: "Voi", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD377", name: "Đỗ Minh  Anh", nickname: "chíp", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD027", name: "Trịnh Hà Anh", nickname: "", classId: 8, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD294", name: "Trần Huy Tuấn  Kiệt", nickname: "voi", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD045", name: "Nguyễn Trần Phương Chi", nickname: "su", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD182", name: "Lê Thế Sơn", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD280", name: "Ngô Thanh  Tùng", nickname: "Sóc", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD410", name: "Trịnh Hà  Quang", nickname: "", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD425", name: "Ngô Hoài  An", nickname: "kẹo", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD462", name: "Trịnh Hoài Thư", nickname: "Lu", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD170", name: "Nguyễn Ngọc Châu Anh", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD360", name: "Lê Gia  Khang", nickname: "bầu", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD382", name: "Phạm Danh Phú", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD195", name: "Vũ Ngọc Khánh", nickname: "Tôm", classId: 9, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD451", name: "Nguyễn Ngọc Linh ", nickname: "Xuka ", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD449", name: "Chử Khôi Nguyên", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD196", name: "Phạm Kiều Linh", nickname: "Tít", classId: 9, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD466", name: "Chu Thạch Tùng", nickname: "", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD498", name: "Mộc Vân", nickname: "Na", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD284", name: "Nguyễn Đặng Châu Anh", nickname: "Bắp Cải", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD006", name: "Hồ Đức Kiên", nickname: "", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD452", name: "Nguyễn Minh Đăng", nickname: "Sóc", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD405", name: "Đào Ngọc  Anh", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD496", name: "Nông Tuệ Gia  Linh ", nickname: "", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD124", name: "Mạc Nam Phong", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD463", name: "Nguyễn Gia Hưng", nickname: "Voi", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD005", name: "Mai Thu Hương", nickname: "", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD220", name: "Nguyễn Trúc Quỳnh", nickname: "", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD342", name: "Lê Thị Minh  Anh", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD473", name: "Phạm Nguyễn Nhật Minh", nickname: "Sumin", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD306", name: "Tăng Thiên Bảo", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD458", name: "Hà An Ngọc ", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD489", name: "Dương Đoàn Anh  Tú", nickname: "Tú", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD424", name: "Lương Đào Quỳnh Anh", nickname: "chip", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD190", name: "Trần Hữu Đăng", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD501", name: "Nguyễn Đức Duy", nickname: "Tin", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD004", name: "Nguyễn Phương Ngọc Huyền", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD073", name: "Lê Vũ Mộc Trà", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD387", name: "Quảng  Đức", nickname: "", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD443", name: "Phạm Diệu An", nickname: "Thỏ", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD475", name: "Đoàn Bảo Lam", nickname: "Thỏ", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD421", name: "Trần Ngọc Anh  Chi", nickname: "muối", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD210", name: "Lê Bảo An", nickname: "Nấm", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD230", name: "Trần Hoàng Phúc", nickname: "Su", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD303", name: "Thành  Đạt", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD378", name: "Nguyễn Phương Linh", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD502", name: "Nguyễn Nhật Anh ", nickname: "Ôỉ ", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD337", name: "Thái An Nhiên", nickname: "bắp", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD343", name: "Lê Bá  Đức", nickname: "cò", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD503", name: "Minh Khôi", nickname: "Thóc", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD495", name: "Nguyễn Quang  Anh ", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD437", name: "Hà Tú Linh", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD427", name: "Tạ Hoàng Minh Khang", nickname: "KUL", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD218", name: "Anh Đức", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD456", name: "Lê An Nhiên ", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD197", name: "Khương Hữu Nghĩa", nickname: "Ben", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD461", name: "Trịnh Gia Bảo", nickname: "Zôn", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD352", name: "Lê Đức  Minh", nickname: "cà phê", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD465", name: "Nguyễn Minh Khôi", nickname: "Cún", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD430", name: "Nguyễn Hải  Anh", nickname: "thỏ", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD314", name: "Ngọc  Diệp", nickname: "", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD499", name: "Hoàng Thành  Đạt", nickname: "", classId: 8, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD431", name: "Nguyễn Hà  Anh", nickname: "mèo", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD015", name: "Nguyễn Khánh Duy", nickname: "", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD417", name: "Nguyễn Ngọc Hà My", nickname: "Nhím", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD186", name: "Nguyễn Uy Vũ", nickname: "Bảo An", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD071", name: "Lê Hải Phong", nickname: "Tí", classId: 9, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD033", name: "Nguyễn Minh Hùng", nickname: "", classId: 8, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD320", name: "Tuấn  Long", nickname: "", classId: 9, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD332", name: "Nguyễn Hoàng Yến Nhi", nickname: "bống", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD441", name: "Ngô Thị Hồng Mai ", nickname: "", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD467", name: "Nguyễn Hà Bảo Anh ", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD438", name: "Hà Minh Hưng", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD372", name: "Trần Bình  Minh", nickname: "Gấu", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD207", name: "Nguyễn Như Nam Anh", nickname: "Bun", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD445", name: "Phạm Bảo Long", nickname: "Bảo Bối", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD455", name: "Vũ Anh Quân ", nickname: "", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD468", name: "Phạm Đức Minh", nickname: "Khoai", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD340", name: "Nguyễn Ngọc Phương  Anh", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD469", name: "Phạm Ngọc Huyền", nickname: "Dâu", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD490", name: "Đinh Thế Công  Minh", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD311", name: "Đậu Minh  Hưng", nickname: "Bon", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD364", name: "Nguyễn Nhật  Minh", nickname: "bắp", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD148", name: "Đỗ Ngọc Bảo Trâm", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD460", name: "Nguyễn Minh Tuấn ", nickname: "Coca", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD187", name: "Nguyễn Như Việt Anh", nickname: "Thỏ", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD381", name: "Đình  Cường", nickname: "", classId: 6, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD333", name: "Nguyễn Nhật  Linh", nickname: "ỈN", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD400", name: "Nguyễn Đức  Mạnh", nickname: "Tôm", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD325", name: "Nguyễn Gia  Khiêm", nickname: "bo", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD459", name: "Cấn Khánh Linh ", nickname: "Xoài", classId: 0, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD201", name: "Thúy Quỳnh", nickname: "Cún", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD407", name: "Lê Minh Thư", nickname: "SU", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD450", name: "Đặng Gia Hân ", nickname: "Bông", classId: 1, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD464", name: "Lưu Quang Khôi", nickname: "Mỡ ", classId: 4, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD114", name: "Hoàng Quốc Bảo", nickname: "", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD365", name: "Mè Đức  Anh", nickname: "tép", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD433", name: "Chu Sơn  Tùng", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD312", name: "Quỳnh Nhi", nickname: "Lana", classId: 7, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD198", name: "Phạm Nguyễn Bảo Ngọc", nickname: "Nấm", classId: 5, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD492", name: "Nguyễn Bảo  Ngân ", nickname: "", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD046", name: "Trần Diệp Chi", nickname: "", classId: 3, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD457", name: "Nguyễn Khôi  Nguyên ", nickname: "Khoai", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD493", name: "Nguyễn Trần Bảo Trâm", nickname: "mía", classId: 2, attendanceStatus: 0, activeStatus: 0},
    {kidId: "HD009", name: "Đoàn Tất Bảo Lâm", nickname: "coca", classId: 1, attendanceStatus: 0, activeStatus: 0},

]

export { kidInfoTest, classInfoTest }